Repository hypermodeinc/dgraph, pull requests merged in 2020-10, with the labels that each got.

#6594 fix(gqlgen): Update gqlgen in go.mod
  go.mod
  go.sum
  graphql/e2e/common/fragment.go
  graphql/schema/schemagen_test.go
Labels: area/graphql

#6620 docs: add documentation for clone backend
  wiki/content/slash-graphql/admin/clone.md
Labels: area/documentation

#6621 docs: add documentation for clone backend
  wiki/content/slash-graphql/admin/clone.md
Labels: area/documentation

#6622 docs: add documentation for clone backend
  wiki/content/slash-graphql/admin/clone.md
Labels: area/documentation

#6624 test: Fix flakiness in group_delete_test.go
  systest/group-delete/group_delete_test.go
  testutil/zero.go
Labels: area/testing

#6628 Chore: run "go fmt" on master.
  systest/group-delete/group_delete_test.go
Labels: area/testing

#6590 (release/v20.07): feat(Dgraph): add utility to export backup data.
  dgraph/cmd/root_ee.go
  ee/backup/run.go
  worker/export.go
  worker/file_handler.go
Labels: area/commercial

#6601 (release/v20.07) build: Makefile to build Dgraph inside docker container
  contrib/docker-build/Makefile
  contrib/docker-build/README.md
  contrib/docker-build/build.sh
  contrib/docker-build/docker-compose.yml
Labels: area/integrations

#6604 Feat(GraphQL): This PR allows to return errors from custom REST endpoint.
  graphql/e2e/custom_logic/cmd/main.go
  graphql/e2e/custom_logic/custom_logic_test.go
  graphql/resolve/resolver.go
Labels: area/graphql

#6646 release/v20.07 - fix(gqlgen): Update gqlgen in go.mod (#6594)
  go.mod
  go.sum
  graphql/e2e/common/fragment.go
  graphql/schema/schemagen_test.go
Labels: area/graphql

#6648 release/20.07: Fix(GraphQL): fix object Linking with `hasInverse`
  graphql/e2e/common/common.go
  graphql/e2e/common/mutation.go
  graphql/resolve/add_mutation_test.yaml
  graphql/resolve/mutation_rewriter.go
Labels: area/graphql

#6527 cherry-pick v20.07: doc: update /admin endpoint documentation. (#6415)
  wiki/content/enterprise-features/binary-backups.md
  wiki/content/graphql/admin/index.md
Labels: area/documentation

#6623 test: Duplicate fields in queries with fragments
  graphql/e2e/common/fragment.go
Labels: area/graphql

#6647 fix(GraphQL Query): Remove extra fields when querying interfaces (#6596)
  graphql/e2e/common/fragment.go
  graphql/resolve/resolver.go
Labels: area/graphql

#6645 fix (graphql): disallowing field names with as
  graphql/schema/gqlschema_test.yml
  graphql/schema/rules.go
  wiki/content/graphql/schema/reserved.md
Labels: area/documentation, area/graphql

#6564 feat(GraphQL): Support authorization with jwk_url
  go.mod
  graphql/authorization/auth.go
  graphql/authorization/utils.go
  graphql/resolve/auth_test.go
  graphql/schema/schemagen.go
  graphql/schema/wrappers_test.go
  testutil/graphql.go
Labels: area/graphql

#6642 docs: Update restore documentation.
  wiki/content/enterprise-features/binary-backups.md
Labels: area/commercial, area/documentation

#6653 (release/v20.07) docs: Update restore documentation.
  wiki/content/enterprise-features/binary-backups.md
Labels: area/documentation

#6652 fix(TestPlugins) Increase sleep timer to prevent connection retries on sleeping cluster
  systest/cluster_setup_test.go
Labels: area/testing

#6584 docs(slash-graphql): Update Slash quick-start guide
  wiki/content/slash-graphql/slash-quick-start.md
  wiki/static/images/slash-graphql/apiexplorer.png
  wiki/static/images/slash-graphql/docexplorer.png
  wiki/static/images/slash-graphql/schema.png
  wiki/static/images/slash-graphql/todos.png
Labels: area/documentation

#6661 fix(GraphQL): This PR reduces polling duration of subscriptions.
  graphql/subscription/poller.go
Labels: area/graphql

#6608 docs: Add a reference to /admin/schema
  wiki/content/graphql/admin/index.md
Labels: area/documentation

#6615 fix(gqlParser): Handle strings with only whitespace in parseID
  gql/parser.go
  gql/parser_test.go
Labels: area/querylang

#6666 Feat(GraphQL): This PR add enable schema cleaning in GraphQL and reduce schema update time.
  graphql/admin/schema.go
  graphql/schema/gqlschema.go
  graphql/schema/schemagen.go
  graphql/schema/schemagen_test.go
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
Labels: area/graphql

#6643 feat(Dgraph): Use Badger with new WAL format.
  dgraph/cmd/alpha/run.go
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/debug/run.go
  dgraph/cmd/debug/wal.go
  dgraph/cmd/live/run.go
  dgraph/cmd/raft-migrate/run.go
  dgraph/cmd/raft-migrate/storage.go
  dgraph/main.go
  go.mod
  go.sum
  posting/index.go
  posting/writer.go
  protos/Makefile
  raftwal/log.go
  systest/loader/loader_test.go
  test.sh
  testutil/backup.go
  worker/config.go
  worker/draft.go
  worker/file_handler.go
  worker/restore.go
  worker/server_state.go
  x/flags.go
  x/metrics.go
  x/x.go
Labels: area/bulk-loader, area/live-loader

#6656 Fix(Dgraph): Type names in exported schema are sorrounded by brackets.
  systest/export/export_test.go
  worker/export.go
Labels: area/testing

#6664 docs: Document restoreStatus GraphQL endpoint.
  wiki/content/enterprise-features/binary-backups.md
Labels: area/commercial, area/documentation

#6663 docs: Document listBackups GraphQL endpoint.
  wiki/content/enterprise-features/binary-backups.md
Labels: area/commercial, area/documentation

#5645 update statement about JSON mutation
  wiki/content/mutations/json-mutation-format.md
Labels: area/documentation

#6685 fix(GraphQL): fix schema tests by adding geo type info to output of clean schema string.
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
Labels: area/graphql

#6660 fix(Auth): fix Poor-man's auth for admin operations
  dgraph/cmd/alpha/admin.go
  dgraph/cmd/alpha/http.go
  dgraph/cmd/alpha/login_ee.go
  dgraph/cmd/alpha/run.go
  edgraph/server.go
  graphql/e2e/admin_auth/admin_auth_test.go
  graphql/e2e/admin_auth/docker-compose.yml
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/web/http.go
  x/x.go
Labels: area/graphql

#6662 feat(GraphQL): add support for IN filter
  graphql/dgraph/graphquery.go
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/schema/generatedSchema.graphql
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/schema/gqlschema.go
  graphql/schema/testdata/schemagen/output/authorization.graphql
  graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
  graphql/schema/testdata/schemagen/output/custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/custom-nested-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-mixed-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-not-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/custom-query-with-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/deprecated.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/output/geo-type.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-type-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse.graphql
  graphql/schema/testdata/schemagen/output/hasInverse_withSubscription.graphql
  graphql/schema/testdata/schemagen/output/hasfilter.graphql
  graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-dgraph-pred.graphql
  graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
  graphql/schema/testdata/schemagen/output/lambda-directive.graphql
  graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
  graphql/schema/testdata/schemagen/output/no-id-field.graphql
  graphql/schema/testdata/schemagen/output/password-type.graphql
  graphql/schema/testdata/schemagen/output/searchables-references.graphql
  graphql/schema/testdata/schemagen/output/searchables.graphql
  graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
  graphql/schema/testdata/schemagen/output/single-type.graphql
  graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
  graphql/schema/testdata/schemagen/output/type-reference.graphql
  graphql/schema/testdata/schemagen/output/type-with-arguments-on-field.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-field-on-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-fields-on-remote-type.graphql
  graphql/schema/testdata/schemagen/output/type-without-orderables.graphql
Labels: area/graphql

#6065 fix(GraphQL): fixes flaky test for subscriptions.
  graphql/e2e/subscription/subscription_test.go
Labels: area/graphql

#6686 cherry-pick v20.07: fix(Auth): fix Poor-man's auth for admin operations (#6660)
  dgraph/cmd/alpha/admin.go
  dgraph/cmd/alpha/http.go
  dgraph/cmd/alpha/login_ee.go
  dgraph/cmd/alpha/run.go
  edgraph/server.go
  graphql/e2e/admin_auth/admin_auth_test.go
  graphql/e2e/admin_auth/docker-compose.yml
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/web/http.go
  x/x.go
Labels: area/graphql

#6581 chore: Updated live loader docs to include ludicrous mode.
  wiki/content/deploy/fast-data-loading.md
Labels: area/documentation

#6702 fix(GraphQL): fix e2e test for in filter
  graphql/e2e/common/query.go
Labels: area/graphql

#6697 [BREAKING/cli-flags] feat(bulk): Use snappy compression by default.
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
Labels: area/bulk-loader

#6705 docs: Fix link to More about Dgraph Zero page.
  wiki/content/deploy/kubernetes.md
Labels: area/documentation

#6710 opt(bulk): Close the stream after done
  dgraph/cmd/bulk/reduce.go
Labels: area/bulk-loader

#6657 docs(Query): Update docs to note that only typed data can be deleted using `S * *`(Docs)
  wiki/content/mutations/delete.md
Labels: area/documentation

#6712 fix(GraphQL): modify jwkUrl test case
  graphql/resolve/auth_test.go
Labels: area/graphql

#6696 docs: add ACL examples and information
  wiki/content/enterprise-features/access-control-lists.md
Labels: area/commercial, area/documentation

#6711 Docs(DQL)Document the `between` function
  wiki/content/query-language/functions.md
Labels: area/documentation

#6709 Docs (Authentication):Fix for DGRAPH-2235 to restore missing admin authentication docs deleted by split-pages Docs PR
  wiki/content/deploy/dgraph-administration.md
  wiki/content/query-language/schema.md
Labels: area/documentation

#6713 docs(theme): Get Started in Style
  wiki/content/_index.md
  wiki/static/images/hero-deco.png
Labels: area/documentation

#6716 Make ACL login error message more generic
  edgraph/access_ee.go
  ee/acl/acl_test.go
  x/x.go
Labels: area/commercial

#6707 fix(GraphQL): This PR fix panic error when we give null value in filter connectives.
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#6718 fix(memory): Allocate KVs via z.Allocator
  algo/packed_test.go
  codec/codec.go
  dgraph/cmd/bulk/count_index.go
  dgraph/cmd/bulk/reduce.go
  dgraph/main.go
  go.mod
  go.sum
  posting/index.go
  posting/list.go
  posting/list_test.go
  posting/mvcc.go
  posting/mvcc_test.go
  protos/pb.proto
  protos/pb/pb.pb.go
  query/outputnode.go
  worker/backup_processor.go
  worker/predicate_move.go
  worker/restore.go
Labels: area/bulk-loader

#6733 fix(GraphQL): fixes flaky test for subscriptions. (#6065)
  graphql/e2e/subscription/subscription_test.go
Labels: area/graphql

#6736 fix(GraphQL): This PR fix panic error when we give null value in filter connectives. (#6707)
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#6734 Feat(GraphQL): This PR add enable schema cleaning in GraphQL and reduce schema update time. (#6666)
  graphql/admin/schema.go
  graphql/schema/gqlschema.go
  graphql/schema/schemagen.go
  graphql/schema/schemagen_test.go
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/input/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/input/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
Labels: area/graphql

#6735 fix(GraphQL): This PR reduces polling duration of subscriptions. (#6661)
  graphql/subscription/poller.go
Labels: area/graphql

#6658 docs: Fix Issues with Docs in local env and docker.
  wiki/README.md
  wiki/content/_index.md
  wiki/content/clients/_index.md
  wiki/content/deploy/_index.md
  wiki/content/design-concepts/_index.md
  wiki/content/dgraph-compared-to-other-databases/index.md
  wiki/content/dql/_index.md
  wiki/content/enterprise-features/_index.md
  wiki/content/faq/index.md
  wiki/content/get-started/index.md
  wiki/content/graphql/_index.md
  wiki/content/graphql/admin/index.md
  wiki/content/graphql/api/_index.md
  wiki/content/graphql/authorization/_index.md
  wiki/content/graphql/custom/_index.md
  wiki/content/graphql/dgraph/index.md
  wiki/content/graphql/directives/index.md
  wiki/content/graphql/how-dgraph-graphql-works/index.md
  wiki/content/graphql/mutations/_index.md
  wiki/content/graphql/overview/index.md
  wiki/content/graphql/queries/_index.md
  wiki/content/graphql/quick-start/index.md
  wiki/content/graphql/schema/_index.md
  wiki/content/graphql/subscriptions/index.md
  wiki/content/graphql/todo-app-tutorial/_index.md
  wiki/content/howto/_index.md
  wiki/content/mutations/_index.md
  wiki/content/query-language/_index.md
  wiki/content/releases/index.md
  wiki/content/slash-graphql/_index.md
  wiki/content/slash-graphql/admin/_index.md
  wiki/content/tips/index.md
  wiki/content/tutorials/index.md
  wiki/docker-compose.yml
  wiki/nginx/docs-docker.conf
  wiki/scripts/docker.sh
Labels: area/commercial, area/documentation, area/graphql

#6592 chore: Add note that @id directive must be string type
  wiki/content/graphql/schema/ids.md
Labels: area/documentation, area/graphql

#6730 docs (fix): fixing incomplete Slash security note
  wiki/content/slash-graphql/security.md
Labels: area/documentation

#6745 doc(fix): security.md
  wiki/content/slash-graphql/security.md
Labels: area/documentation

#6580 Fix(ACL) : Disallow deleting of groot user and guardians group
  edgraph/access_ee.go
  ee/acl/acl_test.go
  query/mutation.go
  systest/bgindex/count_test.go
  systest/online-restore/online_restore_test.go
  x/x.go
Labels: area/commercial

#6651 feat(GraphQL): add support for between filter in GraphQL
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/schema/generatedSchema.graphql
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/schema/gqlschema.go
  graphql/schema/testdata/schemagen/output/authorization.graphql
  graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
  graphql/schema/testdata/schemagen/output/custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/custom-nested-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-mixed-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-not-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/custom-query-with-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/deprecated.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/output/geo-type.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-type-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse.graphql
  graphql/schema/testdata/schemagen/output/hasInverse_withSubscription.graphql
  graphql/schema/testdata/schemagen/output/hasfilter.graphql
  graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-dgraph-pred.graphql
  graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
  graphql/schema/testdata/schemagen/output/lambda-directive.graphql
  graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
  graphql/schema/testdata/schemagen/output/no-id-field.graphql
  graphql/schema/testdata/schemagen/output/password-type.graphql
  graphql/schema/testdata/schemagen/output/searchables-references.graphql
  graphql/schema/testdata/schemagen/output/searchables.graphql
  graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
  graphql/schema/testdata/schemagen/output/single-type.graphql
  graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
  graphql/schema/testdata/schemagen/output/type-reference.graphql
  graphql/schema/testdata/schemagen/output/type-with-arguments-on-field.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-field-on-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-fields-on-remote-type.graphql
  graphql/schema/testdata/schemagen/output/type-without-orderables.graphql
Labels: area/graphql

#6754 fix(Ludicrous): Upserts on list type in Dgraph
  systest/ludicrous/upsert_test.go
  worker/draft.go
Labels: area/mutations

#6759 docs: add a graph traversal example
  wiki/content/query-language/kshortest-path-quries.md
Labels: area/documentation

#6761 fix: correct spelling of "retrieve"
  dgraph/cmd/alpha/run.go
  edgraph/graphql.go
  graphql/admin/cors.go
  graphql/e2e/common/admin.go
  query/query.go
Labels: area/graphql

#6767 fix(test): removing ludicrous mode from the zero init
  systest/ludicrous/docker-compose.yml
  systest/ludicrous/upsert_test.go
Labels: area/testing

#6766 fix(test): Add sleep before running ludicrous mode tests
  systest/ludicrous/upsert_test.go
Labels: area/testing

#6753 docs(Slash): remove slash docs from main repo
  wiki/content/_index.md
  wiki/content/slash-graphql/_index.md
  wiki/content/slash-graphql/admin/_index.md
  wiki/content/slash-graphql/admin/authentication.md
  wiki/content/slash-graphql/admin/backend-modes.md
  wiki/content/slash-graphql/admin/clone.md
  wiki/content/slash-graphql/admin/drop-data.md
  wiki/content/slash-graphql/admin/import-export.md
  wiki/content/slash-graphql/admin/overview.md
  wiki/content/slash-graphql/admin/schema.md
  wiki/content/slash-graphql/advanced-queries.md
  wiki/content/slash-graphql/introduction.md
  wiki/content/slash-graphql/one-click-deploy.md
  wiki/content/slash-graphql/security.md
  wiki/content/slash-graphql/slash-quick-start.md
Labels: area/documentation

#5688 docs: Update docs uid, uid_in and GQL Vars
  wiki/content/query-language/functions.md
  wiki/content/query-language/graphql-variables.md
Labels: area/documentation

#6762 feat(GraphQL): allow duplicate XIDs if only XID value is repeated
  graphql/resolve/add_mutation_test.yaml
  graphql/resolve/mutation_rewriter.go
Labels: area/graphql

#6448 update(docs): information regarding merged PR for background indexing
  wiki/content/query-language/schema.md
Labels: area/documentation

#6787 Update for 20.07.2 and 20.03.6
  wiki/content/releases/index.md
Labels: area/documentation

#6742 feat(Dgraph): Online restores allows to restore a specific backup. (#…
  graphql/admin/endpoints_ee.go
  graphql/admin/restore.go
  protos/pb.proto
  protos/pb/pb.pb.go
  systest/online-restore/online_restore_test.go
  testutil/json.go
  worker/backup_handler.go
  worker/file_handler.go
  worker/online_restore_ee.go
  worker/restore.go
  worker/s3_handler.go
Labels: area/graphql

#6790 docs(slash): fix sidebar
  wiki/config.toml
  wiki/content/slash-graphql/admin/clone.md
  wiki/content/slash-graphql/one-click-deploy.md
  wiki/content/slash-graphql/security.md
Labels: area/documentation

#6773 fix(ludicrous mode): Handle deletes correctly
  edgraph/server.go
  query/mutation.go
  systest/ludicrous/upsert_test.go
  worker/draft.go
Labels: area/testing

#6769 Docs(Dgraph): Update "More about Dgraph Zero" to reflect the output of the /state endpoint, and provide an edit pass
  wiki/content/deploy/dgraph-zero.md
Labels: area/documentation

#6798 Cherry-pick (docs) v20.07: Update docs to note that only typed data can be deleted using `S * *`
  wiki/content/mutations/delete.md
Labels: area/documentation

#6732 Fix(GraphQL): This PR adds input coercing for Integers given in variables and fixes e2e error tests.
  graphql/e2e/common/common.go
  graphql/e2e/common/error.go
  graphql/e2e/common/error_test.yaml
  graphql/schema/request.go
Labels: area/graphql

#6543 docs:Change GraphQL+- references to DQL in docs.
  wiki/content/_index.md
  wiki/content/dgraph-compared-to-other-databases/index.md
  wiki/content/faq/index.md
  wiki/content/get-started/index.md
  wiki/content/query-language/graphql-fundamentals.md
  wiki/content/slash-graphql/admin/backend-modes.md
  wiki/content/slash-graphql/advanced-queries.md
  wiki/content/slash-graphql/introduction.md
  wiki/content/tips/index.md
Labels: area/documentation, area/graphql

#6788 feat(Query): Enable persistent queries in dgraph
  dgraph/cmd/alpha/run_test.go
  dgraph/cmd/bulk/systest/test-bulk-schema.sh
  edgraph/graphql.go
  ee/acl/acl_test.go
  graphql/admin/admin.go
  graphql/e2e/common/admin.go
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/directives/schema_response.json
  graphql/e2e/normal/schema_response.json
  graphql/e2e/schema/schema_test.go
  graphql/schema/request.go
  graphql/web/http.go
  schema/schema.go
  systest/backup/encryption/backup_test.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio/backup_test.go
  systest/export/export_test.go
  systest/mutations_test.go
  systest/queries_test.go
  worker/export.go
  x/keys.go
  x/x.go
Labels: area/graphql, area/schema

#6782 docs (new): Add Geolocation feature to GraphQL docs
  wiki/content/graphql/schema/dgraph-schema.md
  wiki/content/graphql/schema/reserved.md
  wiki/content/graphql/schema/search.md
  wiki/content/graphql/schema/types.md
Labels: area/documentation, area/graphql

#6799 feat(Query): Add cacheControl directive that adds headers in the response
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/schema/generatedSchema.graphql
  graphql/resolve/resolver.go
  graphql/schema/gqlschema.go
  graphql/schema/response.go
  graphql/schema/testdata/schemagen/output/authorization.graphql
  graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
  graphql/schema/testdata/schemagen/output/custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/custom-nested-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-mixed-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-not-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/custom-query-with-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/deprecated.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-all-empty.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-circular.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/output/geo-type.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-type-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse.graphql
  graphql/schema/testdata/schemagen/output/hasInverse_withSubscription.graphql
  graphql/schema/testdata/schemagen/output/hasfilter.graphql
  graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-dgraph-pred.graphql
  graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
  graphql/schema/testdata/schemagen/output/lambda-directive.graphql
  graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
  graphql/schema/testdata/schemagen/output/no-id-field.graphql
  graphql/schema/testdata/schemagen/output/password-type.graphql
  graphql/schema/testdata/schemagen/output/searchables-references.graphql
  graphql/schema/testdata/schemagen/output/searchables.graphql
  graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
  graphql/schema/testdata/schemagen/output/single-type.graphql
  graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
  graphql/schema/testdata/schemagen/output/type-reference.graphql
  graphql/schema/testdata/schemagen/output/type-with-arguments-on-field.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-field-on-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-fields-on-remote-type.graphql
  graphql/schema/testdata/schemagen/output/type-without-orderables.graphql
  graphql/schema/testdata/schemagen/output/union.graphql
  graphql/schema/wrappers.go
  graphql/web/http.go
Labels: area/graphql

#6800 docs: clarify exact order for trigram and term indexes when specified together
  wiki/content/query-language/schema.md
Labels: area/documentation

#6809 docs:v20.03 docs trigram term order
  wiki/content/query-language/index.md
Labels: area/documentation

#6808 docs:v20.07 docs trigram term order
  wiki/content/query-language/schema.md
Labels: area/documentation

#6807 fix(GraphQL): fix lambda service
  graphql/e2e/directives/docker-compose.yml
  graphql/e2e/normal/docker-compose.yml
Labels: area/graphql

#6781 feat(GraphQL): Auth on Interfaces should work correctly while querying them.
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/schema.graphql
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
  graphql/schema/auth.go
  graphql/schema/testdata/schemagen/output/auth-on-interfaces.graphql
  graphql/schema/testdata/schemagen/output/union.graphql
  graphql/schema/wrappers.go
Labels: area/graphql

#6770 docs: (new) Add documentation for count feature in GraphQL
  wiki/content/graphql/queries/and-or-not.md
  wiki/content/graphql/queries/count.md
Labels: area/documentation, area/graphql

#6779 Feat(GraphQL): This PR adds auth switch in GraphQL authorization header.
  graphql/authorization/auth.go
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/debug_off/debugoff_test.go
  graphql/e2e/auth/schema.graphql
  graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
  graphql/e2e/auth_closed_by_default/docker-compose.yml
  graphql/e2e/common/common.go
  graphql/resolve/auth_closed_by_default_add_test.yaml
  graphql/resolve/auth_closed_by_default_delete_test.yaml
  graphql/resolve/auth_closed_by_default_query_test.yaml
  graphql/resolve/auth_closed_by_default_update_test.yaml
  graphql/resolve/auth_test.go
  testutil/graphql.go
Labels: area/graphql

#6814 GraphQL (Docs): Document the /admin/schema/validate endpoint
  wiki/content/graphql/admin/index.md
Labels: area/documentation, area/graphql
