Repository hypermodeinc/dgraph, pull requests merged in 2020-12, with the labels that each got.

#7027 release/20.07 - chore: Fix gql fuzz tests
  gql/fuzzit.sh
Labels: area/querylang

#6985 Feat(GraphQL): Add aggregate query at root level
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/delete_mutation_test.go
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/directives/test_data.json
  graphql/e2e/normal/test_data.json
  graphql/e2e/schema/generatedSchema.graphql
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/resolve/resolver.go
  graphql/resolve/schema.graphql
  graphql/schema/gqlschema.go
  graphql/schema/testdata/schemagen/output/auth-on-interfaces.graphql
  graphql/schema/testdata/schemagen/output/authorization.graphql
  graphql/schema/testdata/schemagen/output/comments-and-descriptions.graphql
  graphql/schema/testdata/schemagen/output/custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/custom-query-mixed-types.graphql
  graphql/schema/testdata/schemagen/output/custom-query-with-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/deprecated.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-on-concrete-type-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/dgraph-reverse-directive-with-interfaces.graphql
  graphql/schema/testdata/schemagen/output/field-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/field-with-reverse-predicate-in-dgraph-directive.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-custom-mutation.graphql
  graphql/schema/testdata/schemagen/output/filter-cleanSchema-directLink.graphql
  graphql/schema/testdata/schemagen/output/generate-directive.graphql
  graphql/schema/testdata/schemagen/output/geo-type.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-interface.graphql
  graphql/schema/testdata/schemagen/output/hasInverse-with-type-having-directive.graphql
  graphql/schema/testdata/schemagen/output/hasfilter.graphql
  graphql/schema/testdata/schemagen/output/ignore-unsupported-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-dgraph-pred.graphql
  graphql/schema/testdata/schemagen/output/interface-with-id-directive.graphql
  graphql/schema/testdata/schemagen/output/interface-with-no-ids.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types-and-password.graphql
  graphql/schema/testdata/schemagen/output/interfaces-with-types.graphql
  graphql/schema/testdata/schemagen/output/lambda-directive.graphql
  graphql/schema/testdata/schemagen/output/no-id-field-with-searchables.graphql
  graphql/schema/testdata/schemagen/output/no-id-field.graphql
  graphql/schema/testdata/schemagen/output/password-type.graphql
  graphql/schema/testdata/schemagen/output/searchables-references.graphql
  graphql/schema/testdata/schemagen/output/searchables.graphql
  graphql/schema/testdata/schemagen/output/single-type-with-enum.graphql
  graphql/schema/testdata/schemagen/output/single-type.graphql
  graphql/schema/testdata/schemagen/output/type-implements-multiple-interfaces.graphql
  graphql/schema/testdata/schemagen/output/type-reference.graphql
  graphql/schema/testdata/schemagen/output/type-with-arguments-on-field.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-field-on-dgraph-type.graphql
  graphql/schema/testdata/schemagen/output/type-with-custom-fields-on-remote-type.graphql
  graphql/schema/testdata/schemagen/output/union.graphql
  graphql/schema/wrappers.go
  graphql/schema/wrappers_test.go
Labels: area/graphql

#7022 Feat(GraphQL): Add Aggregation Queries at Child Level
  graphql/e2e/auth/auth_test.go
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/resolve/resolver.go
  graphql/schema/gqlschema.go
Labels: area/graphql

#7012 Fix(GraphQL): Fix password query rewriting in release/v20.11
  graphql/e2e/common/admin.go
  graphql/e2e/common/query.go
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#7020 docs (chore): Add build/install instructions for macOS
  README.md
Labels: area/documentation

#7021 docs (chore): Update Live Loader's ludicrous mode notes
  wiki/content/deploy/fast-data-loading.md
Labels: area/documentation

#7026 release/20.11 - chore: Fix gql fuzz tests
  gql/fuzzit.sh
Labels: area/querylang

#7044 release/v20.11-slash: chore: Fix gql fuzz tests
  gql/fuzzit.sh
Labels: area/querylang

#7016 chore(test): Refactor GraphQL tests to use best practices (GRAPHQL-885)
  dgraph/cmd/alpha/run.go
  go.mod
  go.sum
  graphql/e2e/admin_auth/poorman_auth/admin_auth_test.go
  graphql/e2e/admin_auth/poorman_auth_with_acl/admin_auth_test.go
  graphql/e2e/auth/add_mutation_test.go
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/debug_off/debugoff_test.go
  graphql/e2e/auth/delete_mutation_test.go
  graphql/e2e/auth/update_mutation_test.go
  graphql/e2e/common/admin.go
  graphql/e2e/common/common.go
  graphql/e2e/common/error.go
  graphql/e2e/common/mutation.go
  graphql/e2e/common/schema.go
  graphql/e2e/custom_logic/custom_logic_test.go
  graphql/e2e/schema/schema_test.go
  graphql/e2e/subscription/subscription_test.go
  testutil/client.go
  testutil/graphql.go
  testutil/schema.go
Labels: area/graphql

#7041 docs (chore): Minor adjustments to Ludicrous mode
  wiki/content/deploy/ludicrous-mode.md
Labels: area/documentation

#7049 docs (fix): Update kubernetes links to match 20.07 config files
  wiki/content/deploy/kubernetes.md
Labels: area/documentation

#7030 release v20.07: don't compare counter in successive state calls (#6967)
  graphql/e2e/common/admin.go
Labels: area/graphql

#7033 fix(DQL): ignore ordering of indexes in schema with eq function
  systest/queries_test.go
  wiki/content/query-language/functions.md
  worker/tokens.go
Labels: area/documentation, area/indexes

#7034 fix(DQL): ignore ordering of indexes in schema with eq function
  systest/queries_test.go
  wiki/content/query-language/index.md
  worker/tokens.go
Labels: area/indexes

#7036 [docs] removed note about order for term and trigram
  wiki/content/query-language/schema.md
Labels: area/documentation

#7037 [docs] removed note about order for term and trigram since it has been fixed
  wiki/content/query-language/schema.md
Labels: area/documentation

#7038 [docs] removed note about order for term and trigram since it has been fixed
  wiki/content/query-language/index.md
Labels: area/documentation

#6981 Docs (clarification) Note proper use and meaning of --replicas flag
  wiki/content/deploy/cluster-setup.md
Labels: area/documentation

#7056 docs (chore): adjust search-filtering.md format
  wiki/content/graphql/queries/search-filtering.md
Labels: area/documentation, area/graphql

#6723 fix(Wiki): Fix typo in add.md in wiki.
  wiki/content/graphql/mutations/add.md
Labels: area/documentation

#6442 docs(GraphQL): Update Dgraph authorization format in Todo tutorial
  wiki/content/graphql/todo-app-tutorial/todo-auth0-jwt.md
Labels: area/documentation

#7057 docs (fix): Update Dgraph authorization format in tutorial (#6442)
  wiki/content/graphql/todo-app-tutorial/todo-auth0-jwt.md
Labels: area/documentation, area/graphql

#7032 [docs] : rephrase + added example to query logging section
  wiki/content/deploy/log-format.md
Labels: area/documentation

#7071 test: Fix health test.
  graphql/e2e/common/admin.go
Labels: area/graphql

#7053 fix(GraphQL): This PR allows repetition of fields inside implementing type which are present in interface and also allow to inherit field of same name of type ID from multiple interfaces.
  graphql/e2e/directives/schema.graphql
  graphql/e2e/normal/schema.graphql
  graphql/schema/gqlschema.go
  graphql/schema/gqlschema_test.yml
  graphql/schema/schemagen.go
Labels: area/graphql

#7078 [docs] : rephrase + added example to query logging section (#7032)
  wiki/content/deploy/log-format.md
Labels: area/documentation

#7055 [docs] : rephrase for "--replicas" flag usage (related to PR: #6981)
  wiki/content/deploy/cluster-setup.md
Labels: area/documentation

#7084 [docs] added backup policy
  wiki/content/deploy/production-checklist.md
Labels: area/documentation

#7088 docs: Fix typos. Update backup policy section.
  wiki/content/deploy/production-checklist.md
  wiki/content/mutations/upsert-block.md
Labels: area/documentation

#7087 fix(Dgraph): Revert to snake case flags
  compose/compose.go
  dgraph/cmd/alpha/run.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/live/load-uids/load_test.go
  dgraph/cmd/live/run.go
  dgraph/cmd/migrate/run.go
  dgraph/cmd/root.go
  dgraph/cmd/zero/raft.go
  dgraph/cmd/zero/run.go
  ee/acl/acl.go
  ee/acl/acl_test.go
  ee/acl/run_ee.go
  ee/backup/run.go
  ee/enc/util_ee.go
  ee/enc/vault_ee.go
  graphql/admin/admin.go
  graphql/schema/rules.go
  systest/backup/encryption/backup_test.go
  systest/backup/minio/backup_test.go
  systest/bulk_live_fixture_test.go
  systest/cluster_setup_test.go
  testutil/backup.go
  tlstest/certrequest/certrequest_test.go
  tlstest/certrequireandverify/certrequireandverify_test.go
  tlstest/certverifyifgiven/certverifyifgiven_test.go
  upgrade/change_v20.07.0.go
  upgrade/upgrade.go
  worker/file_handler.go
  worker/online_restore_ee.go
  worker/worker.go
  x/flags.go
  x/profile.go
  x/sentry_integration.go
  x/tls_helper.go
  x/x.go
Labels: area/bulk-loader, area/commercial, area/graphql, area/live-loader, area/testing

#7080 Fix(GraphQL): Refactor output of query/mutation rewriting
  graphql/admin/add_group.go
  graphql/admin/current_user.go
  graphql/admin/schema.go
  graphql/admin/update_group.go
  graphql/dgraph/graphquery.go
  graphql/resolve/mutation.go
  graphql/resolve/mutation_rewriter.go
  graphql/resolve/query.go
  graphql/resolve/query_rewriter.go
Labels: area/graphql

#6991 fix: added comment docstring for ExportInput format
  graphql/admin/admin.go
Labels: area/graphql

#7090 release/20.11-slash - revert to snake case flags
  compose/compose.go
  dgraph/cmd/alpha/run.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/live/load-uids/load_test.go
  dgraph/cmd/live/run.go
  dgraph/cmd/migrate/run.go
  dgraph/cmd/root.go
  dgraph/cmd/zero/raft.go
  dgraph/cmd/zero/run.go
  ee/acl/acl.go
  ee/acl/acl_test.go
  ee/acl/run_ee.go
  ee/backup/run.go
  ee/enc/util_ee.go
  ee/enc/vault_ee.go
  graphql/admin/admin.go
  graphql/schema/rules.go
  systest/backup/encryption/backup_test.go
  systest/backup/minio/backup_test.go
  systest/bulk_live_fixture_test.go
  systest/cluster_setup_test.go
  testutil/backup.go
  tlstest/certrequest/certrequest_test.go
  tlstest/certrequireandverify/certrequireandverify_test.go
  tlstest/certverifyifgiven/certverifyifgiven_test.go
  upgrade/change_v20.07.0.go
  upgrade/upgrade.go
  worker/file_handler.go
  worker/online_restore_ee.go
  worker/worker.go
  x/flags.go
  x/profile.go
  x/sentry_integration.go
  x/tls_helper.go
  x/x.go
Labels: area/bulk-loader, area/commercial, area/graphql, area/live-loader, area/testing

#7100 perf(GraphQL): Part-1: Pagination for root user query is applied at root auth query (GRAPHQL-854)
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
  query/query.go
Labels: area/graphql

#7103 fix(GraphQL): don't update cacheMb if not specified by user (GRAPHQL-888)
  graphql/admin/config.go
Labels: area/graphql

#7106 v20.07: fix(GraphQL): don't update cacheMb if not specified by user (GRAPHQL-…
  graphql/admin/config.go
Labels: area/graphql

#7105 perf(GraphQL): Part-2: Remove unnecessary `dgraph.uid : uid` selections for auth queries (GRAPHQL-854)
  graphql/resolve/auth_add_test.yaml
  graphql/resolve/auth_delete_test.yaml
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/auth_test.go
  graphql/resolve/auth_update_test.yaml
  graphql/resolve/query_rewriter.go
Labels: area/graphql

#7107 perf(GraphQL): Part-3: Filter child auth queries as early as possible (GRAPHQL-854)
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
Labels: area/graphql

#7108 docs (chore): Add missing Discard(ctx) to Dgo client
  wiki/content/clients/go.md
Labels: area/documentation

#7094 Fix(GraphQL): Add support for repeatitive fields in aggregate query
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#7099 fix: added comment docstring for ExportInput format (#6991)
  graphql/admin/admin.go
Labels: area/graphql

#7097 fix: added comment docstring for ExportInput format (#6991)
  graphql/admin/admin.go
Labels: area/graphql

#7113 docs (chore): add note regarding RDF queries
  wiki/content/clients/go.md
Labels: area/documentation

#7110 Fix(bulk): Correctly append all the slices of cbuf while reduce phase
  dgraph/cmd/bulk/reduce.go
  systest/bulk_live/common/bulk_live_cases.go
Labels: area/bulk-loader

#7111 perf(GraphQL): Part-4: Child auth queries are derived from auth filtered parents (GRAPHQL-854)
  graphql/resolve/auth_delete_test.yaml
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/auth_test.go
  graphql/resolve/query_rewriter.go
Labels: area/graphql

#7117 fix(GraphQL): Correctly apply order for root auth query (GRAPHQL-854)
  graphql/e2e/auth/auth_test.go
  graphql/resolve/auth_delete_test.yaml
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
Labels: area/graphql

#7119 Fix(GraphQL): Fix Aggregate queries on empty data
  graphql/e2e/auth/auth_test.go
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/resolve/resolver.go
Labels: area/graphql

#7121 docs (feat): Add live loader upsert predicate example
  wiki/content/deploy/_index.md
  wiki/content/deploy/dgraph-administration.md
  wiki/content/deploy/fast-data-loading/_index.md
  wiki/content/deploy/fast-data-loading/bulk-loader.md
  wiki/content/deploy/fast-data-loading/live-loader.md
  wiki/content/deploy/fast-data-loading/overview.md
  wiki/content/deploy/kubernetes.md
  wiki/content/deploy/ports-usage.md
  wiki/content/mutations/batch-mutations.md
Labels: area/documentation

#7104 GraphQL(Docs): Documentation for Aggregate Queries
  wiki/content/graphql/queries/aggregate.md
  wiki/content/graphql/queries/and-or-not.md
  wiki/content/graphql/queries/cached-results.md
  wiki/content/graphql/queries/cascade.md
  wiki/content/graphql/queries/count.md
  wiki/content/graphql/queries/order-page.md
  wiki/content/graphql/queries/persistent-queries.md
  wiki/content/graphql/queries/skip-include.md
Labels: area/documentation, area/graphql

#7124 docs (fix): Update RDF example code in live-loader
  wiki/content/deploy/fast-data-loading/live-loader.md
Labels: area/documentation

#7120 chore(test):enabling tests to run with race flag enabled
  systest/1million/1million_test.go
  systest/21million/bulk/run_test.go
  systest/21million/ludicrous/run_test.go
  systest/_customtok/anagram/main.go
  systest/_customtok/cidr/main.go
  systest/_customtok/cidr/main_test.go
  systest/_customtok/factor/main.go
  systest/_customtok/rune/main.go
  systest/bulk_live/common/bulk_live_cases.go
  systest/bulk_live/common/bulk_live_fixture.go
  t/t.go
  testutil/bulk.go
  testutil/docker.go
  testutil/exec.go
Labels: area/testing

#7009 fix(GraphQL): fix internal Aliases name generation
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#7128 release(v20.11): unmarshal snapshot onto zerosnapshot instead of membershipState (#7125)
  dgraph/cmd/debug/wal.go
  dgraph/cmd/zero/raft.go
Labels: area/graphql, area/integrations

#7130 chore: fix a broken test
  graphql/resolve/query_test.yaml
Labels: area/graphql

#7132 fix(GraphQL): fix internal Aliases name generation (#7009)
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
Labels: area/graphql

#7039 feat(graphql): adding auth token support for regexp, in and arrays
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/schema.graphql
  graphql/e2e/auth/test_data.json
  graphql/e2e/common/common.go
  graphql/schema/auth.go
  graphql/schema/auth_schemas_test.yaml
Labels: area/graphql

#7019 fix(graphql): adding support for @id with type other than strings
  graphql/e2e/common/common.go
  graphql/e2e/common/mutation.go
  graphql/e2e/common/query.go
  graphql/e2e/directives/schema.graphql
  graphql/e2e/directives/schema_response.json
  graphql/e2e/directives/test_data.json
  graphql/e2e/normal/schema.graphql
  graphql/e2e/normal/schema_response.json
  graphql/e2e/normal/test_data.json
  graphql/resolve/mutation_rewriter.go
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/schema/dgraph_schemagen_test.yml
  graphql/schema/gqlschema.go
  graphql/schema/gqlschema_test.yml
  graphql/schema/rules.go
  graphql/schema/schemagen.go
  graphql/schema/wrappers.go
Labels: area/graphql

#7137 docs (chore): cherry-picking docs for 20.11 release
  wiki/content/deploy/_index.md
  wiki/content/deploy/dgraph-administration.md
  wiki/content/deploy/fast-data-loading/_index.md
  wiki/content/deploy/fast-data-loading/bulk-loader.md
  wiki/content/deploy/fast-data-loading/live-loader.md
  wiki/content/deploy/fast-data-loading/overview.md
  wiki/content/deploy/kubernetes.md
  wiki/content/deploy/ports-usage.md
  wiki/content/graphql/queries/aggregate.md
  wiki/content/graphql/queries/and-or-not.md
  wiki/content/graphql/queries/cached-results.md
  wiki/content/graphql/queries/cascade.md
  wiki/content/graphql/queries/count.md
  wiki/content/graphql/queries/order-page.md
  wiki/content/graphql/queries/persistent-queries.md
  wiki/content/graphql/queries/skip-include.md
  wiki/content/mutations/batch-mutations.md
Labels: area/documentation, area/graphql

#7079 [docs] rephrase query logging + examples
  wiki/content/deploy/index.md
Labels: area/documentation

#7133 fix(GraphQL): This PR addd input coercion from single object to list and fix panic when we pass single ID in filter as a string.
  go.mod
  go.sum
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/resolve/mutation_rewriter.go
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  graphql/schema/rules.go
  graphql/schema/validation_rules.go
Labels: area/graphql

#7154 fix(bulk): fixing bulk loader when encryption + mtls is enabled
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
Labels: area/bulk-loader

#7155 fix(bulk): fixing bulk loader when encryption + mtls is enabled (#7154)
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
Labels: area/bulk-loader

#7142 docs: Update GraphQL interface implementation reference
  wiki/content/graphql/schema/types.md
Labels: area/documentation, area/graphql

#7141 fix(GraphQL): Fix race conditions found in tests
  graphql/admin/admin.go
  graphql/admin/schema.go
  graphql/resolve/resolver.go
  graphql/subscription/poller.go
Labels: area/graphql

#7163 docs(graphql): Fix link to lambda fields.
  wiki/content/graphql/lambda/overview.md
Labels: area/documentation, area/graphql

#7164 docs(graphql): Fix link to lambda fields. (#7163)
  wiki/content/graphql/lambda/overview.md
Labels: area/documentation, area/graphql

#7165 feat(bulk): Add /jemalloc HTTP endpoint.
  dgraph/cmd/bulk/run.go
Labels: area/bulk-loader

#7145 Docs(GraphQL): Correct Deep Mutations Docs (follow-up rewording / typo fix)
  wiki/content/graphql/mutations/deep.md
Labels: area/documentation, area/graphql

#7162 docs (fix): Add decryption key information to binary-backups.md
  wiki/content/enterprise-features/binary-backups.md
Labels: area/commercial, area/documentation

#7160 topic(Docs): Remove link to github issues for issues related to dgraph
  wiki/content/tutorial-1/index.md
  wiki/content/tutorial-2/index.md
  wiki/content/tutorial-3/index.md
  wiki/content/tutorial-4/index.md
  wiki/content/tutorial-5/index.md
  wiki/content/tutorial-6/index.md
  wiki/content/tutorial-7/index.md
  wiki/content/tutorial-8/index.md
  wiki/content/tutorials/index.md
Labels: area/documentation

#7171 fix(Chunker): JSON parsing performance
  chunker/json_parser.go
  chunker/json_parser_test.go
Labels: area/facets, area/parsing, area/performance, kind/enhancement

#6708 docs: Fix link to More about Dgraph Zero page.
  wiki/content/deploy/kubernetes.md
Labels: area/documentation

#6582 chore: Update ludicrous mode docs to mention the way it assigns times…
  wiki/content/deploy/ludicrous-mode.md
Labels: area/documentation

#7175 chore(systest): add missing variable to RunLiveCases
  systest/bulk_live/common/bulk_live_cases.go
Labels: area/testing

#7173 fix(bulk): fixing bulk loader when tls + encryption is enabled
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
Labels: area/bulk-loader

#7172 docs: Add a Migration section
  wiki/content/migration/_index.md
  wiki/content/migration/dgraph-compared-to-other-databases.md
  wiki/content/migration/graphql-dgraph.md
  wiki/content/migration/loading-csv-data.md
  wiki/content/migration/migrate-dgraph-1-1.md
Labels: area/documentation

#6440 added documentation for type of roles in API keys
  wiki/content/graphql/todo-app-tutorial/deploy.md
  wiki/static/images/graphql/tutorial/todo/slash-graphql-1.png
  wiki/static/images/graphql/tutorial/todo/slash-graphql-2.png
  wiki/static/images/graphql/tutorial/todo/slash-graphql-3.png
  wiki/static/images/graphql/tutorial/todo/slash-graphql-4.png
  wiki/static/images/graphql/tutorial/todo/slash-graphql-5.png
Labels: area/documentation

#5694 docs(deploy): Add more examples for whitelist config.
  wiki/content/deploy/dgraph-administration.md
Labels: area/documentation

#7077 [docs]example on how to turn on/off query logging dynamically
  wiki/content/deploy/log-format.md
Labels: area/documentation

#5761 docs(Deploy): Add "poor man's ACL" wording in auth token docs.
  wiki/content/deploy/dgraph-administration.md
Labels: area/documentation

#7035 fix(DQL): ignore ordering of indexes in schema with eq function (DGRA…
  systest/queries_test.go
  wiki/content/query-language/index.md
  worker/tokens.go
Labels: area/indexes

#3996 docs: Fix grammar.
  wiki/content/deploy/dgraph-administration.md
  wiki/content/query-language/functions.md
Labels: area/documentation

#6818 docs(GraphQL): Correct Deep Mutation examples
  wiki/content/graphql/mutations/deep.md
Labels: area/documentation

#7185 Improve documentation rebased
  wiki/content/get-started/index.md
  wiki/content/query-language/schema.md
  wiki/content/query-language/type-system.md
Labels: area/documentation

#5693 docs: add more details about Reverse edges and Reverse Facets
  wiki/content/mutations/reverse-edges.md
Labels: area/documentation

#7192 docs : Rephrase of the query logging section
  wiki/content/deploy/log-format.md
Labels: area/documentation

#7187 [docs] Suggestion for disk IOPS
  wiki/content/deploy/production-checklist.md
Labels: area/documentation

#7195 docs: Suggestion for disk IOPS (#7187)
  wiki/content/deploy/production-checklist.md
Labels: area/documentation

#7194 docs: Suggestion for disk IOPS (#7187)
  wiki/content/deploy/production-checklist.md
Labels: area/documentation

#7183 Docs: rename gql+- to dql
  wiki/content/tips/index.md
Labels: area/documentation

#7191 [docs] example on how to turn on/off query logging dynamically
  wiki/content/deploy/log-format.md
Labels: area/documentation

#7178 [docs] added example on how to turn on/off query logging dynamically
  wiki/content/deploy/index.md
Labels: area/documentation

#7177 [docs]example on how to turn on/off query logging dynamically (#7077)
  wiki/content/deploy/log-format.md
Labels: area/documentation

#6817 docs(DQL): Tweaked DQL Introduction
  wiki/content/query-language/graphql-fundamentals.md
Labels: area/documentation

#7179 Docs(Migration): "Migrate from Dgraph v1.0 to Newer Versions"
  wiki/content/migration/migrate-dgraph-1-1.md
Labels: area/documentation

#7199 docs: Fix link to lambda directive.
  wiki/content/graphql/directives/index.md
Labels: area/documentation, area/graphql

#7198 docs: Fix link to lambda directive.
  wiki/content/graphql/directives/index.md
Labels: area/documentation, area/graphql

#6400 chore(docs): add Ratel Docs
  wiki/content/ratel/_index.md
  wiki/content/ratel/backups.md
  wiki/content/ratel/cluster.md
  wiki/content/ratel/connection.md
  wiki/content/ratel/console.md
  wiki/content/ratel/schema.md
  wiki/static/images/ratel/ratel_acl.png
  wiki/static/images/ratel/ratel_backup.png
  wiki/static/images/ratel/ratel_console.png
  wiki/static/images/ratel/ratel_extra.png
  wiki/static/images/ratel/ratel_schema.png
  wiki/static/images/ratel/ratel_schema_bulk.png
  wiki/static/images/ratel/ratel_schema_types.png
  wiki/static/images/ratel/ratel_ui.png
  wiki/static/images/ratel/ratel_zero.png
Labels: area/documentation

#7216 docs (chore): Fix code indentation in cascade.md
  wiki/content/graphql/queries/cascade.md
Labels: area/documentation, area/graphql

#7215 docs: Fix Netlify previews.
  netlify.toml
  wiki/content/deploy/download.md
  wiki/content/deploy/kubernetes.md
  wiki/content/enterprise-features/access-control-lists.md
  wiki/content/graphql/custom/directive.md
  wiki/content/graphql/lambda/overview.md
  wiki/content/tutorial-2/index.md
  wiki/content/tutorial-6/index.md
  wiki/content/tutorials/index.md
  wiki/scripts/local.sh
Labels: area/documentation

#7167 fix(test) : http test to be more resilient and fix race
  dgraph/cmd/alpha/http_test.go
  dgraph/cmd/alpha/metrics_test.go
  dgraph/cmd/alpha/run_test.go
  systest/mutations_test.go
  worker/proposal_test.go
Labels: area/testing

#7222 docs (feat): Adds Java client library documentation
  wiki/content/clients/java.md
Labels: area/documentation

#7224 fix(test): fixing test cases for race enabled tests
  systest/1million/1million_test.go
  systest/21million/common/run_queries.go
  testutil/backup.go
Labels: area/testing

#7213 docs (feat): Add JS client library documentation
  wiki/content/clients/javascript.md
  wiki/content/clients/javascript/_index.md
  wiki/content/clients/javascript/grpc.md
  wiki/content/clients/javascript/http.md
Labels: area/documentation

#7225 docs (feat): Adds Python client library documentation
  wiki/content/clients/python.md
Labels: area/documentation

#7223 docs: how to properly bulk load
  wiki/content/deploy/fast-data-loading/bulk-loader.md
Labels: area/documentation

#7231 docs: how to properly bulk load (#7223)
  wiki/content/deploy/fast-data-loading/bulk-loader.md
Labels: area/documentation

#7232 docs: how to properly bulk load (#7223)
  wiki/content/deploy/fast-data-loading.md
Labels: area/documentation

#7227 docs (feat): Adds C# client library documentation
  wiki/content/clients/_index.md
  wiki/content/clients/c-sharp.md
  wiki/content/clients/csharp.md
Labels: area/documentation

#7234 docs: add notes regarding restricted JSON values
  wiki/content/mutations/json-mutation-format.md
Labels: area/documentation
