Repository hypermodeinc/dgraph, pull requests merged in 2021-11, with the labels that each got.

#8069 fix(race): fix multiple race conditions
  posting/list.go
  posting/oracle.go
  worker/draft.go
Labels: area/graphql

#8093 test(acl): Test reverse edge access with dgraph.all.
  ee/acl/acl_test.go
Labels: area/commercial

#8092 perf(rollup): use NSplit API from sroar to improve rollup performance
  dgraph/cmd/alpha/run.go
  dgraph/cmd/bulk/count_index.go
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/debug/run.go
  go.mod
  go.sum
  posting/index_test.go
  posting/list.go
  posting/list_test.go
  posting/mvcc.go
  posting/writer.go
  worker/backup.go
  worker/restore_map.go
  worker/server_state.go
  worker/task.go
  worker/worker_test.go
Labels: area/bulk-loader

#8101 cherry: fix(state): fix hex to uint64 response of list of namespaces (#8091)
  graphql/admin/state.go
  x/keys.go
Labels: area/graphql

#8102 build: Update release.sh.
  contrib/release.sh
Labels: area/integrations
