Repository hypermodeinc/dgraph, pull requests merged in 2021-08, with the labels that each got.

#7970 cherry-pick: fix: fixing graphql schema update when the data is restored + skippin…
  ee/audit/interceptor_ee.go
  graphql/admin/admin.go
  graphql/admin/schema.go
  worker/graphql_schema.go
  worker/online_restore.go
Labels: area/commercial, area/graphql

#7974 contrib: Implement side-by-side comparison tool
  contrib/sbs/.gitignore
  contrib/sbs/go.mod
  contrib/sbs/go.sum
  contrib/sbs/sbs.go
Labels: area/integrations

#7979 fix(sbs): Print final result only after all workers are done
  contrib/sbs/sbs.go
Labels: area/integrations

#7982 perf(sroar): Use latest sroar and add histogram in the sbs tool
  contrib/sbs/go.mod
  contrib/sbs/go.sum
  contrib/sbs/sbs.go
  contrib/sbs/utils.go
  go.mod
  go.sum
Labels: area/integrations

#7985 fix(live): quote the xid when doing upsert
  dgraph/cmd/live/run.go
Labels: area/live-loader

#7983 fix(live): quote the xid when doing upsert
  dgraph/cmd/live/run.go
Labels: area/live-loader

#7993 feat(acl): allow access to all the predicates using wildcard (#7991)
  edgraph/access_ee.go
  ee/acl/acl_test.go
  worker/acl_cache.go
Labels: area/commercial

#7994 feat(acl): allow access to all the predicates using wildcard (#7991)
  edgraph/access_ee.go
  ee/acl/acl_test.go
  worker/acl_cache.go
Labels: area/commercial

#7822 chore(tests): refactor parser tests
  gql/alias_order_lang_fragment_regex_test.go
  gql/filter_test.go
  gql/parser_test.go
  gql/query_test.go
  gql/schema_count_graphql_vars_test.go
Labels: area/querylang

#8007 fix: add validation of null values with correct order of graphql rule validation
  go.mod
  go.sum
  graphql/schema/rules.go
Labels: area/graphql

#8008 fix: add validation of null values with correct order of graphql rule validation
  go.mod
  go.sum
  graphql/schema/rules.go
Labels: area/graphql
