Repository hypermodeinc/dgraph, pull requests merged in 2022-11, with the labels that each got.

#8406 Artifact fix to directly get dgraph binary from tar
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#8358 fix(Makefile): Improve 'install' target behavior
  Makefile
  dgraph/Makefile
Labels: arm64

#8413 chore(ci): fix breaking tests
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: arm64

#8365 fix(deps): update dependencies on badger + ristretto
  go.mod
  go.sum
Labels: arm64

#8422 fix(cd) badger artifacts
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#8425 fix(cd): cd changes for badger
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#8439 fix(chore): Update CODEOWNERS
  .github/CODEOWNERS
Labels: area/integrations

#8440 fix(cicd): run on draft PRs
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#8436 chore(ci): fix arm workflows + minor CI cleanup
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
Labels: area/integrations

#8418 fix(ACL): Prevents permissions overrride and merges acl cache to persist permissions across different namespaces
  edgraph/access_ee.go
  ee/acl/acl_test.go
  systest/multi-tenancy/basic_test.go
  testutil/json.go
  testutil/multi_tenancy.go
  testutil/utils.go
  worker/acl_cache.go
Labels: area/commercial

#8442 fix(admin): make config changes to pass through gog middlewares (#8014)
  graphql/admin/admin.go
Labels: area/graphql, cherry-pick-22.0.2

#8435 fix(fragment): merge the nested fragments fields (#8075)
  graphql/e2e/common/fragment.go
  graphql/schema/request.go
Labels: area/graphql, cherry-pick-22.0.2

#8452 fix(query): Do not execute filters if there are no source uids (#7962…
  query/query.go
  query/query1_test.go
Labels: cherry-pick-22.0.2

#8449 Fix(GraphQL): Make mutation rewriting tests more robust (#7768)
  graphql/resolve/auth_add_test.yaml
  graphql/resolve/auth_test.go
  graphql/resolve/auth_update_test.yaml
  graphql/resolve/mutation.go
  graphql/resolve/mutation_rewriter.go
Labels: area/graphql, cherry-pick-22.0.2

#8455 fix(chore): Change remaining Copyright year
  LICENSE.md
  Makefile
  compose/Makefile
  contrib/scripts/license.py
  contrib/scripts/license.sh
  contrib/tlstest/Makefile
  dgraph/Makefile
  protos/Makefile
  protos/depcheck.sh
  t/Makefile
Labels: area/integrations
