Repository hypermodeinc/dgraph, pull requests merged in 2022-12, with the labels that each got.

#8432 Fix(lsbackup): Fix profiler in lsBackup (#7729)
  ee/backup/run.go
Labels: area/commercial, cherry-pick-22.0.2

#8441 fix(sort): Only filter out nodes with positive offsets. (#8077)
  query/common_test.go
  query/query0_test.go
  worker/sort.go
Labels: cherry-pick-22.0.2

#8431 fix(DQL): optimize query for has function with offset. (#7727)
  protos/pb.proto
  protos/pb/pb.pb.go
  query/query.go
  query/query1_test.go
  worker/task.go
Labels: cherry-pick-22.0.2

#8474 chore(ci): pin runners to ubuntu-20.04
  .github/workflows/cd-dgraph.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#8471 fix(pagination): Fix after for regexp, match functions (#7700)
  query/query1_test.go
  query/query2_test.go
  query/query3_test.go
  worker/match.go
  worker/trigram.go
Labels: cherry-pick-22.0.2

#8479 Add tests for ResetPassword
  ee/acl/acl_test.go
  systest/multi-tenancy/basic_test.go
  testutil/multi_tenancy.go
Labels: area/testing, area/commercial

#8491 fix(ci/cd): pin linux deps
  contrib/Dockerfile
Labels: area/integrations

#8500 fix(ci): reduce triggers by disabling on draft runs
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
Labels: area/integrations

#8492 fix(ci/cd): Fix failing test packages for ARM CI runs
  .github/workflows/ci-dgraph-tests-arm64.yml
  contrib/local-test/README.md
  contrib/local-test/docker-compose-lambda.yml
  graphql/e2e/custom_logic/cmd/Dockerfile
Labels: area/graphql, area/integrations

#8503 fix(ci): resolve systest failures on arm
  .github/workflows/ci-dgraph-tests-arm64.yml
  Makefile
  systest/backup/minio-large/docker-compose.yml
  systest/backup/minio/docker-compose.yml
  systest/export/docker-compose.yml
  t/Makefile
  t/t.go
Labels: area/testing, area/integrations

#8520 fix(cd): adds arm job
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#8549 fix(ci): reduce cron runs for self-hosted runners
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
Labels: area/integrations

#8506 fix(ACL): Prevents permissions overrride and merges acl cache to persist permissions across different namespaces (#8418)
  edgraph/access_ee.go
  ee/acl/acl_test.go
  systest/multi-tenancy/basic_test.go
  testutil/json.go
  testutil/multi_tenancy.go
  testutil/utils.go
  worker/acl_cache.go
Labels: area/testing, area/enterprise

#8507 fix(chore): Add more logging for cloud instances
  edgraph/server.go
  graphql/admin/admin.go
  graphql/admin/config.go
  wiki/content/graphql/admin/index.md
  worker/draft.go
  worker/worker.go
  x/config.go
  x/x.go
Labels: area/documentation, area/graphql
