Repository hypermodeinc/dgraph, pull requests merged in 2023-04, with the labels that each got.

#8782 simplify test setup in query package
  query/common_test.go
Labels: area/testing, area/core, go

#8789 dgraphtest: add support for export
  dgraphtest/cluster.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/local_cluster.go
  query/upgrade_test.go
  systest/incremental-restore/incremental_restore_test.go
Labels: area/testing, area/core, go

#8774 Fix wal replay issue during rollup
  dgraph/cmd/bulk/reduce.go
  dgraph/cmd/debug/run.go
  posting/index.go
  posting/list.go
  posting/list_test.go
  posting/mvcc.go
  posting/mvcc_test.go
  worker/draft.go
  worker/predicate_move.go
  worker/restore_map.go
Labels: area/testing, area/bulk-loader, area/core, go

#8790 chore(cd): add badger binary to dgraph docker image
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#8794 chore(changelog): v23 rc1 changelog
  CHANGELOG.md
Labels: area/documentation

#8795 fix(changelog): lower case naming convention
  CHANGELOG.md
Labels: area/documentation

#8715 chore(changelog): add changelog for cloud
  CHANGELOG_CLOUD.md
Labels: area/documentation, dgraph

#8798 fix(ci): frequency fix
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
Labels: area/integrations

#8804 chore: remove unused build tag
  tok/stopwords_test.go
Labels: area/testing, go

#8807 chore(test): fix frequently failing NFS-backup tests
  systest/backup/nfs-backup/Dockerfile
  systest/backup/nfs-backup/docker-compose.yml
Labels: area/testing

#8770 chore(ci): add upgrade test workflow
  .github/workflows/ci-dgraph-upgrade-tests.yml
  dgraphtest/cluster.go
  dgraphtest/local_cluster.go
  query/query0_test.go
  query/upgrade_test.go
  systest/audit_encrypted/audit_test.go
Labels: area/integrations
