Repository hypermodeinc/dgraph, pull requests merged in 2023-01, with the labels that each got.

#8553 rename SensitiveByteSlice to Sensitive
  chunker/chunk.go
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/debug/run.go
  dgraph/cmd/decrypt/decrypt.go
  dgraph/cmd/live/run.go
  ee/backup/run.go
  ee/enc/util_ee.go
  ee/flags.go
  ee/vault_ee.go
  filestore/filestore.go
  filestore/local_files.go
  filestore/remote_files.go
  graphql/schema/gqlschema.go
  graphql/schema/rules.go
  graphql/schema/schemagen.go
  raftwal/log.go
  raftwal/storage.go
  systest/backup/common/utils.go
  systest/backup/encryption/backup_test.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio-large/backup_test.go
  systest/backup/minio/backup_test.go
  systest/backup/multi-tenancy/backup_test.go
  worker/backup_common.go
  worker/config.go
  worker/restore.go
  x/config.go
  x/logger.go
  x/types.go
  x/x_test.go
Labels: area/testing, area/graphql, area/bulk-loader, area/live-loader, slash-to-main, area/commercial

#8516 chore(debug): add summary to show LSM tree and namespace size (#7891)
  dgraph/cmd/debug/run.go
Labels: slash-to-main

#8568 chore(logs): add logs to track dropped proposals (#8012)
  worker/draft.go
Labels: slash-to-main

#8569 test(systest): avoid host volume mount in minio test
  dgraph/docker-compose.yml
  systest/1million/1million_test.go
  systest/21million/bulk/run_test.go
  systest/bulk_live/bulk/docker-compose.yml
  systest/bulk_live/common/bulk_live_fixture.go
  systest/bulk_live/live/docker-compose.yml
  systest/ldbc/alpha.yml
  systest/ldbc/ldbc_test.go
  testutil/bulk.go
  testutil/minio.go
Labels: area/testing

#8574 fix(GraphQL): Pass on HTTP request headers for subscriptions (#7806) (#7807)
  graphql/admin/http.go
Labels: area/graphql, slash-to-main

#8560 fix(debug): Check length of wal entry before parsing
  dgraph/cmd/debug/wal.go
Labels: slash-to-main

#8577 fix(ci): unpin curl
  contrib/Dockerfile
Labels: area/integrations

#8565 opt(schema): Optimize populateSchema() (#8068) (#8071)
  worker/schema.go
Labels: slash-to-main

#8573 fix(zero): fix update membership to make bulk tablet proposal instead of multiple small (#8090)
  dgraph/cmd/zero/zero.go
Labels: slash-to-main

#8571 fix(GraphQL): Nested Auth Rules not working properly. (#7915) (#8084)
  graphql/e2e/auth/auth_test.go
  graphql/resolve/auth_query_test.yaml
  graphql/resolve/query_rewriter.go
Labels: area/graphql, slash-to-main

#8592 fix(ci): adjust cron schedules
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
Labels: area/integrations

#8478 chore(ci): Capture coverage from bulk load and LDBC tests
  .github/workflows/ci-dgraph-code-coverage.yml
  systest/ldbc/docker-compose.yml
  systest/ldbc/ldbc_test.go
  t/t.go
  testutil/bulk.go
Labels: area/testing, area/graphql, area/integrations

#8461 chore(github): update feature request issue template
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: area/integrations

#8564 feat(cdc): Add superflag to enable TLS without CA or certs (#7946)
  worker/server_state.go
  worker/sink_handler.go
  x/tls_helper.go
Labels: slash-to-main

#8562 opt(schema): Load schema and types using Stream framework
  schema/schema.go
  worker/draft.go
  worker/groups.go
  worker/mutation.go
  worker/online_restore_ee.go
Labels: area/schema, slash-to-main

#8612 remove ludicrous mode from the code
  compose/compose.go
  dgraph/cmd/alpha/run.go
  dgraph/cmd/live/batch.go
  dgraph/cmd/live/run.go
  edgraph/server.go
  posting/list.go
  systest/21million/ludicrous/docker-compose.yml
  systest/21million/ludicrous/run_test.go
  systest/21million/test-21million.sh
  systest/ludicrous/1predicate-c.schema
  systest/ludicrous/1predicate.schema
  systest/ludicrous/docker-compose.yml
  systest/ludicrous/queries/query-001
  systest/ludicrous/run_test.go
  systest/ludicrous/test.sh
  systest/ludicrous/upsert_test.go
  t/t.go
  testutil/bulk.go
  worker/cdc_ee.go
  worker/draft.go
  worker/server_state.go
  x/config.go
Labels: area/testing, area/live-loader

#8554 Make the /admin/backup and /admin/export API asynchronous
  dgraph/cmd/alpha/admin.go
  dgraph/cmd/alpha/admin_backup.go
  go.mod
  go.sum
  graphql/admin/admin.go
  graphql/admin/export.go
  graphql/e2e/schema/schema_test.go
  systest/export/export_test.go
  worker/export_test.go
Labels: slash-to-main

#8572 fix: fixing audit logs for websocket connections (#8048) (#8053)
  edgraph/access_ee.go
  edgraph/server.go
  ee/audit/audit_ee.go
  ee/audit/interceptor.go
  ee/audit/interceptor_ee.go
  graphql/admin/http.go
  x/jwt_helper.go
  x/x.go
Labels: area/graphql, slash-to-main, area/commercial

#8511 Cherry-pick namespace aware drop data
  edgraph/access_ee.go
  edgraph/server.go
  posting/index.go
  posting/oracle.go
  systest/backup/multi-tenancy/backup_test.go
  worker/backup_ee.go
  worker/cdc_ee.go
  worker/draft.go
  worker/restore_map.go
Labels: area/testing, area/enterprise, area/graphql, area/bulk-loader, area/live-loader, slash-to-main

#8628 fix(linter): address gosimple linter reports & errors
  .golangci.yml
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/bulk/schema.go
  query/outputnode.go
  query/query.go
  upgrade/upgrade.go
Labels: area/bulk-loader

#8627 fix: fixing audit logs for websocket connections (#8048) (#8053)
  edgraph/access_ee.go
  edgraph/server.go
  ee/audit/audit_ee.go
  ee/audit/interceptor.go
  ee/audit/interceptor_ee.go
  graphql/admin/http.go
  x/jwt_helper.go
  x/x.go
Labels: area/graphql, slash-to-main, area/commercial

#8559 fix(restore): consider the banned namespaces while bumping (#7839)
  worker/restore_map.go
Labels: slash-to-main
