Repository hypermodeinc/dgraph, pull requests merged in 2023-09, with the labels that each got.

#8968 feat(restore): add support for namespace aware restore
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/config.go
  dgraphtest/local_cluster.go
  go.mod
  graphql/admin/admin.go
  graphql/admin/endpoints_ee.go
  graphql/admin/restore.go
  protos/pb.proto
  protos/pb/pb.pb.go
  systest/integration2/incremental_restore_test.go
  systest/online-restore/namespace-aware/restore_test.go
  worker/online_restore.go
  worker/restore_map.go
Labels: area/testing, area/graphql, area/core, go

#8995 perf(query): use quickselect instead of sorting while pagination
  types/select.go
  types/sort.go
  types/sort_test.go
  worker/sort.go
Labels: area/core, go

#8988 fix(restore): allow incrementalFrom to be 1 in restore API
  systest/integration2/incremental_restore_test.go
  worker/online_restore.go
Labels: area/testing, area/core, go

#9005 ci: update version in readme
  README.md
Labels: area/documentation

#9002 ci(runners): use larger github hosted runners + reduce cron frequency
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-integration2-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
Labels: area/integrations
