Repository hypermodeinc/dgraph, pull requests merged in 2023-08, with the labels that each got.

#8926 fix(upgrade): look for version string in logs bottom up
  dgraphtest/image.go
  dgraphtest/local_cluster.go
Labels: go

#8930 chore(alpha): add logs for processing entries in applyCh
  worker/draft.go
Labels: area/core, go

#8931 sec(acl): convert x.Sensitive to string type for authn hash
  edgraph/server.go
  edgraph/server_test.go
Labels: area/testing, go

#8929 feat(query): add feature flag normalize-compatibility-mode (#8845)
  dgraph/cmd/alpha/run.go
  dgraph/cmd/zero/pgp_test.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  query/normalize_feature_flag_test.go
  query/outputnode.go
  worker/server_state.go
  x/config.go
Labels: area/testing, area/core, go

#8941 perf(query): Improve Intersection with UID pack
  algo/uidlist.go
  algo/uidlist_test.go
Labels: area/testing, go

#8945 doc(zero): add comments in Zero and clarify naming
  dgraph/cmd/zero/assign.go
  dgraph/cmd/zero/zero.go
Labels: go

#8944 fix(live): replace panic in live loader with errors (#7798)
  dgraph/cmd/live/run.go
Labels: area/live-loader, go

#8942 perf(query): speed up parsing of a huge query
  edgraph/server.go
Labels: go

#8953 Revert "chore(graphql): upgrade gqlparser to v2.2.2 (#8917)"
  dgraphtest/config.go
  dgraphtest/dgraph.go
  go.mod
  go.sum
  systest/integration2/graphql_schema_auth_test.go
Labels: area/testing, go

#8948 chore: upgrade bleve to v2.3.9
  go.mod
  go.sum
  tok/bleve.go
  tok/stemmers.go
  tok/stemmers_test.go
  tok/stopwords.go
  tok/stopwords_test.go
Labels: area/testing, go

#7739 chore(contrib) - fixes for Vault
  contrib/config/vault/docker/README.md
  contrib/config/vault/docker/dgraph_alpha_config.yaml
  contrib/config/vault/docker/vault/payload_alpha_secrets.json
Labels: area/integrations

#8943 fix(dgraph): convert numbers correctly in SuperFlags (#7712)
  dgraph/cmd/root.go
  dgraph/cmd/root_test.go
Labels: area/testing, go

#8937 fix(acl): allow data deletion for non-reserved predicates
  ee/acl/acl_test.go
  query/common_test.go
  query/integration_test.go
  query/mutation.go
  query/mutation_test.go
  query/query0_test.go
  query/upgrade_test.go
  systest/bgindex/count_test.go
Labels: area/core, go

#8954 test(upgrade): add v20.11 upgrade tests in query package
  dgraphtest/cluster.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/local_cluster.go
  ee/acl/upgrade_test.go
  query/upgrade_test.go
  systest/license/upgrade_test.go
  systest/multi-tenancy/upgrade_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, area/core, go

#8956 chore: update cron job frequency to reset github notifications
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-integration2-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#8961 fix(export): Escape MySQL column names
  dgraph/cmd/migrate/dump.go
Labels: go

#8960 [feat] Add build Codename to Telemetry data
  telemetry/telemetry.go
  x/init.go
Labels: area/core, go

#8955 chore(docs): remove release instructions from contrib
  CONTRIBUTING.md
Labels: area/documentation

#8962 fix(acl): revert the error changed in #8937
  ee/acl/acl_test.go
  query/mutation.go
  systest/bgindex/count_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, area/core, go

#8959 Chore(DQL and Telemetry): Rename GQLPM to DQL
  dgraph/cmd/alpha/run_test.go
  dql/parser.go
  edgraph/server.go
  graphql/resolve/query_rewriter.go
  query/query.go
  telemetry/telemetry.go
Labels: area/querylang, area/graphql, area/core, go

#8965 test(upgrade): skip test for dgraph version when the bug is not fixed
  dgraphtest/.gitignore
  dgraphtest/config.go
  dql/parser.go
  query/mutation_test.go
Labels: area/testing, area/core, go

#8967 chore: fix linter warnings after golanci upgrade
  graphql/schema/rules.go
  worker/sort.go
Labels: area/graphql, area/core, go

#8973 fix(increment): fix example for --cloud command (#7903)
  dgraph/cmd/increment/increment.go
Labels: go

#8970 test(upgrade): handle different versions of Dgraph for --telemetry flag
  dgraphtest/config.go
  dgraphtest/dgraph.go
Labels: go

#8975 chore(restore): add more logs for restore request (#8050)
  graphql/admin/restore.go
  worker/online_restore.go
  worker/restore_map.go
Labels: area/graphql, area/core, go

#8974 docs(README): remove macOS build references #7685
  README.md
  paper/dgraph.tex
Labels: area/documentation

#8972 fix(restore): use different map directory for each group (#8047)
  ee/backup/run.go
  worker/online_restore.go
  worker/restore_map.go
Labels: area/core, go

#8912 feat(acl): support more JWT algorithms for ACL
  dgraph/cmd/alpha/run.go
  dgraph/cmd/zero/zero_test.go
  dgraphtest/.gitignore
  dgraphtest/config.go
  dgraphtest/data/enc-key
  dgraphtest/data/hmac-secret
  dgraphtest/dgraph.go
  dgraphtest/ee.go
  dgraphtest/image.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  dgraphtest/namespace.go
  dgraphtest/paths.go
  edgraph/access_ee.go
  edgraph/access_ee_test.go
  edgraph/server.go
  edgraph/server_test.go
  ee/acl/acl_integration_test.go
  ee/acl/jwt_algo_test.go
  ee/flags.go
  ee/keys_ee.go
  go.mod
  go.sum
  graphql/authorization/auth.go
  graphql/e2e/admin_auth/poorman_auth_with_acl/admin_auth_test.go
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/debug_off/debugoff_test.go
  graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
  graphql/resolve/auth_test.go
  graphql/subscription/poller.go
  systest/integration2/bulk_loader_test.go
  testutil/graphql.go
  testutil/utils.go
  worker/config.go
  worker/groups.go
  x/config.go
  x/jwt_helper.go
Labels: area/testing, area/enterprise, area/core, go

#8978 fix(export): Support for any s3 endpoint
  x/minioclient.go
Labels: area/core, go

#8969 fix(restore): use custom type for sensitive fields
  graphql/admin/admin.go
  graphql/admin/list_backups.go
  graphql/admin/restore.go
  protos/pb.proto
  protos/pb/pb.pb.go
  protos/pb/sensitive.go
  worker/backup.go
  worker/backup_handler.go
  x/minioclient.go
Labels: area/graphql, area/core, go

#8827 add @unique constraint support in schema for new predicates
  dgraph/cmd/live/batch.go
  dgraph/cmd/live/run.go
  dgraphtest/cluster.go
  edgraph/server.go
  go.mod
  protos/pb.proto
  protos/pb/pb.pb.go
  schema/parse.go
  schema/schema.go
  systest/unique_test.go
  worker/mutation.go
  worker/schema.go
Labels: area/schema, area/core, go

#8896 test(upgrade): add upgrade tests for systest/plugin
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  systest/plugin/integration_test.go
  systest/plugin/plugin_test.go
  systest/plugin/upgrade_test.go
Labels: area/testing, go

#8894 test(upgrade): add upgrade tests for systest/queries-and-mutations
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/local_cluster.go
  systest/mutations-and-queries/integration_test.go
  systest/mutations-and-queries/mutations_test.go
  systest/mutations-and-queries/queries_test.go
  systest/mutations-and-queries/upgrade_test.go
Labels: area/testing, go

#8984 test(upgrade): add upgrade tests for v20.11 for ee/acl
  dgraphtest/cluster.go
  dgraphtest/local_cluster.go
  ee/acl/acl_test.go
  ee/acl/upgrade_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, go
