Repository hypermodeinc/dgraph, pull requests merged in 2023-07, with the labels that each got.

#8893 chore(restore): add log message when restore fails
  graphql/admin/restore.go
Labels: area/graphql, area/core, go

#8899 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/integrations

#8792 test(acl): add upgrade tests for ee/acl package
  dgraphtest/acl.go
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/paths.go
  ee/acl/acl_curl_test.go
  ee/acl/acl_integration_test.go
  ee/acl/acl_test.go
  ee/acl/integration_test.go
  ee/acl/upgrade_test.go
  systest/incremental-restore/incremental_restore_test.go
  systest/multi-tenancy/basic_test.go
  systest/multi-tenancy/upgrade_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, go

#8901 chore: add changelog for v23.0.1
  CHANGELOG.md
Labels: area/documentation

#8903 fix(bulk): enable running bulk loader with only gql schema
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/bulk/run.go
  dgraphtest/cluster.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  systest/integration2/bulk_loader_test.go
  systest/integration2/incremental_restore_test.go
Labels: area/testing, area/bulk-loader, go

#8895 fix: compilation on 32bit
  worker/queue.go
  worker/restore_reduce.go
  xidmap/trie.go
Labels: area/core, go

#8906 chore(upgrade): increase the duration of the CI workflow
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
Labels: area/integrations

#8907 chore(upgrade): increase the job duration limit to 12h
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
Labels: area/integrations

#8890 Chore(raft): Add debug logs to print all transactions
  posting/list.go
  worker/draft.go
  x/debug.go
  x/keys.go
  x/nodebug.go
Labels: area/testing, area/core, go

#8902 add upgrade tests for systest/license package
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/local_cluster.go
  go.mod
  go.sum
  systest/license/integration_test.go
  systest/license/license_test.go
  systest/license/upgrade_test.go
Labels: area/testing, go

#8908 doc(restore): add docs for mutations in between incremental restores
  dgraphtest/local_cluster.go
  systest/integration2/incremental_restore_test.go
  worker/online_restore.go
Labels: area/testing, area/core, go

#8897 chore(test): add workaround for multiple groot issue in export-import
  dgraphtest/cluster.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  edgraph/server.go
  ee/acl/upgrade_test.go
  query/query3_test.go
  query/query4_test.go
  systest/multi-tenancy/upgrade_test.go
Labels: area/testing, area/core, go

#8918 chore(upgrade): run upgrade tests for v23.0.1
  dgraphtest/cluster.go
  dgraphtest/config.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  dgraphtest/paths.go
Labels: go

#8639 feat(alpha): support RDF response via http query request (#8004)
  Makefile
  dgraph/cmd/alpha/http.go
  dgraph/cmd/alpha/http_test.go
Labels: dgraph

#8923 fix(upgrade): check commit SHA to find running dgraph version
  dgraphtest/config.go
  dgraphtest/local_cluster.go
Labels: go
