Repository hypermodeinc/dgraph, pull requests merged in 2023-05, with the labels that each got.

#8791 chore(CI): add paths to ignore
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations, dgraph

#8816 chore: wait longer for login to work
  dgraphtest/cluster.go
  dgraphtest/local_cluster.go
Labels: go

#8818 chore: fix flaky test TestGetAccessJwt
  edgraph/access_ee_test.go
Labels: area/testing, go

#8820 chore(changelog): v23 changelog
  CHANGELOG.md
Labels: area/documentation

#8808 chore(core): Update comment about how drop op behaves with rollups
  posting/list.go
Labels: area/testing, area/core, go

#8824 chore(changelog): add cves to changelog
  CHANGELOG.md
Labels: area/documentation

#8826 chore(changelog): update changelog in release branch
  CHANGELOG.md
Labels: area/documentation

#8832 fix failing oss build
  .github/workflows/ci-dgraph-tests.yml
  ee/acl/run.go
  ee/audit/run_ee_test.go
  systest/backup/common/utils.go
Labels: area/enterprise, area/enterprise/acl, go

#8829 dgraphtest: print container logs if the test fails
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  dgraphtest/config.go
  dgraphtest/local_cluster.go
  query/upgrade_test.go
  systest/incremental-restore/incremental_restore_test.go
Labels: area/testing, area/core, go

#8839 chore(readme): update readme for v23
  README.md
Labels: area/documentation

#8796 `fix`: Made a change for the ldbc test which will fail the test if file download fails.
  t/t.go
Labels: area/testing, go

#8841 fix(bulk): removed buffer max size
  dgraph/cmd/bulk/reduce.go
Labels: area/bulk-loader, go

#8842 dgraphtest: small fixes to dgraphtest lib
  dgraphtest/config.go
  dgraphtest/local_cluster.go
Labels: go

#8834 chore(ci): add workflow for OSS build + unit tests
  .github/workflows/ci-dgraph-oss-build.yml
Labels: area/integrations
