Repository hypermodeinc/dgraph, pull requests merged in 2023-06, with the labels that each got.

#8844 chore: add functions to kill alpha, improve restore check in dgraphtest
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
Labels: go

#8851 chore: waitForRestore should check for receiving snapshot
  dgraphtest/cluster.go
Labels: go

#8853 chore: simplify upgrade testing on single node
  query/upgrade_test.go
Labels: area/testing, area/core, go

#8859 chore(ci): checkout merge commit on pull-request-target
  .github/workflows/ci-dgraph-code-coverage.yml
Labels: area/integrations

#8863 chore: use `git` cmd tool for checkout a git hash
  .github/workflows/ci-dgraph-upgrade-tests.yml
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  query/upgrade_test.go
Labels: go

#8864 chore(ci): fix test coverage workflow
  .github/workflows/ci-dgraph-code-coverage.yml
Labels: area/integrations

#8868 chore: get rid of go-git dependency and use git cmd tool
  dgraphtest/cluster.go
  dgraphtest/image.go
  dgraphtest/paths.go
  go.mod
  go.sum
  systest/multi-tenancy/basic_test.go
Labels: go

#8845 feat(query): add feature flag list-in-normalize
  dgraph/cmd/alpha/run.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  query/normalize_feature_flag_test.go
  query/outputnode.go
  worker/server_state.go
  x/config.go
Labels: area/testing, area/core, go

#8870 chore: improve a couple of functions in dgraphtest
  dgraphtest/cluster.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/local_cluster.go
  query/normalize_feature_flag_test.go
  systest/multi-tenancy/basic_test.go
Labels: area/testing, area/core, go

#8757 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/integrations

#8873 fix(security): remove pull_request_target from coverage workflow
  .github/workflows/ci-dgraph-code-coverage.yml
Labels: area/integrations

#8875 Revert "feat(query): add feature flag list-in-normalize (#8845)"
  dgraph/cmd/alpha/run.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  query/normalize_feature_flag_test.go
  query/outputnode.go
  worker/server_state.go
  x/config.go
Labels: area/testing, area/core, go

#8878 test: print more logs if the upgrade tests fail
  .github/workflows/ci-dgraph-upgrade-tests.yml
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  dgraphtest/paths.go
  systest/multi-tenancy/upgrade_test.go
Labels: area/testing, go

#8879 ci: change code owners file
  .github/CODEOWNERS
Labels: area/integrations

#8882 chore(zero): improve error message while unmarshalling WAL
  dgraph/cmd/zero/raft.go
Labels: go

#8883 chore(test): add support for Export Import upgrade strategy
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  dgraphtest/paths.go
  query/cloud_test.go
  query/upgrade_test.go
Labels: area/testing, area/core, go

#8858 Fix zero's health endpoint to return json response
  dgraph/cmd/zero/http.go
  dgraph/cmd/zero/zero_test.go
Labels: go
