Repository hypermodeinc/dgraph, pull requests merged in 2023-02, with the labels that each got.

#8561 fix(groot): do not upsert groot for all namespaces on restart
  dgraph/cmd/bulk/mapper.go
  dgraph/cmd/bulk/run.go
  edgraph/access_ee.go
  ee/acl/run.go
Labels: slash-to-main

#8551 fix(tests): Added Backup/Restore test for NFS.
  graphql/e2e/schema/schema_test.go
  systest/acl/restore/acl_restore_test.go
  systest/backup/common/utils.go
  systest/backup/encryption/backup_test.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio-large/backup_test.go
  systest/backup/minio/backup_test.go
  systest/backup/multi-tenancy/backup_test.go
  systest/backup/nfs-backup/backup_test.go
  systest/backup/nfs-backup/docker-compose.yml
  systest/export/export_test.go
  systest/online-restore/online_restore_test.go
  t/t.go
  testutil/backup.go
  testutil/client.go
  testutil/utils.go
  worker/export_test.go
Labels: area/testing, area/integrations, area/live-loader

#8563 fix(restore): Set kv version to restoreTs for all keys (#7930)
  worker/restore_map.go
Labels: slash-to-main

#8566 fix(probe): do not contend for lock in lazy load (#8037) (#8041)
  graphql/admin/admin.go
Labels: slash-to-main

#8601 Store namespace in predicate as a hex separated by a hyphen to prevent json marshal issues
  dgraph/cmd/alpha/http_test.go
  dgraph/cmd/alpha/upsert_test.go
  dgraph/cmd/zero/oracle.go
  edgraph/server.go
  graphql/admin/state.go
  posting/index.go
  posting/list_test.go
  systest/backup/filesystem/backup_test.go
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095641.969/r9-g1.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095641.969/r9-g2.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095641.969/r9-g3.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095716.130/r21-g1.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095716.130/r21-g2.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095716.130/r21-g3.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095726.320/r26-g1.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095726.320/r26-g2.backup
  systest/backup/filesystem/data/to_restore/3/dgraph.20210517.095726.320/r26-g3.backup
  systest/backup/filesystem/data/to_restore/3/manifest.json
  worker/backup.go
  worker/backup_ee.go
  worker/backup_manifest.go
  worker/groups.go
  worker/online_restore.go
  worker/restore_map.go
  x/keys.go
  x/keys_test.go
  x/x.go
Labels: area/testing, slash-to-main, area/commercial

#8652 fix(build): Update dockerfile to use cache busting and reduce image size
  contrib/Dockerfile
Labels: area/integrations

#8567 fix(proposals): Incremental proposal key for zero proposals (#8005)
  dgraph/cmd/zero/raft.go
  dgraph/cmd/zero/zero_test.go
  worker/draft.go
  worker/proposal.go
  x/x.go
Labels: slash-to-main

#8625 feat(cloud): add shared-instance flag in limit superflag in alpha (#7770)
  dgraph/cmd/alpha/run.go
  edgraph/access_ee.go
  systest/acl/restore/acl_restore_test.go
  systest/backup/multi-tenancy/backup_test.go
  systest/cloud/cloud_test.go
  systest/cloud/docker-compose.yml
  systest/multi-tenancy/basic_test.go
  testutil/client.go
  testutil/docker.go
  testutil/multi_tenancy.go
  testutil/utils.go
  worker/server_state.go
  x/config.go
  x/minioclient.go
Labels: area/testing, slash-to-main

#8644 fix(ci): Uncomment draft PR logic
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#8662 chore(test): upgrade graphql tests to use go 1.19
  contrib/scripts/functions.sh
  graphql/e2e/custom_logic/cmd/Dockerfile
  graphql/e2e/custom_logic/cmd/go.mod
  graphql/e2e/custom_logic/cmd/go.sum
Labels: area/graphql

#8649 chore(other): Rename Master's references remaining
  .gitignore
  CONTRIBUTING.md
  README.md
  contrib/standalone/Makefile
  dgraph/cmd/alpha/login_ee.go
  dgraph/cmd/root_ee.go
  edgraph/access_ee.go
  edgraph/access_ee_test.go
  edgraph/multi_tenancy_ee.go
  ee/README.md
  ee/acl/acl.go
  ee/acl/acl_curl_test.go
  ee/acl/acl_test.go
  ee/acl/run_ee.go
  ee/acl/utils.go
  ee/audit/audit_ee.go
  ee/audit/interceptor_ee.go
  ee/audit/run_ee.go
  ee/backup/run.go
  ee/enc/util_ee.go
  ee/keys_ee.go
  ee/vault_ee.go
  graphql/admin/endpoints_ee.go
  wiki/content/graphql/admin/index.md
  worker/acl_cache.go
  worker/acl_cache_test.go
  worker/backup_ee.go
  worker/backup_handler.go
  worker/backup_manifest.go
  worker/cdc_ee.go
  worker/multi_tenancy_ee.go
  worker/online_restore.go
  worker/restore_map.go
  worker/restore_reduce.go
Labels: area/documentation, area/graphql, area/integrations, area/commercial

#8646 Added automated test to test multitenant --limit flag
  systest/multi-tenancy/basic_test.go
  systest/multi-tenancy/docker-compose.yml
  testutil/multi_tenancy.go
Labels: area/testing

#8607 chore(CI): Update Labeler
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: area/integrations

#8643 chore(test): Integration tests for advanced backup/restore scenarios
  graphql/e2e/common/common.go
  graphql/e2e/multi_tenancy/multi_tenancy_test.go
  systest/backup/advanced-scenarios/127-Namespace/backup_test.go
  systest/backup/advanced-scenarios/127-Namespace/docker-compose.yml
  systest/backup/common/utils.go
Labels: area/testing, area/graphql

#8680 chore(ci): run CI jobs on release branches
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#8679 fix(parser): Check order of inputs before evaluating nested eq func
  dql/parser.go
  dql/parser_test.go
Labels: area/querylang, go

#8691 Improvements in 127+ namespace test
  systest/backup/advanced-scenarios/127-Namespace/backup_test.go
  systest/backup/common/utils.go
Labels: area/testing, go

#8703 fix(ci) increase frequency
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations
