Repository hypermodeinc/dgraph, pull requests merged in 2023-03, with the labels that each got.

#8710 chore(ci): pipeline changes release_pipeline_to_tags
  .github/workflows/cd-dgraph.yml
Labels: area/integrations, v23.0.0-beta

#8700 `chore`: Integration test for acl to nonacl backup/restore and vice versa
  systest/backup/advanced-scenarios/acl-nonAcl/backup_test.go
  systest/backup/advanced-scenarios/acl-nonAcl/docker-compose.yml
Labels: area/testing, go

#8693 `chore`: Integration test for Deleted Namespace
  graphql/e2e/common/common.go
  systest/backup/advanced-scenarios/deleted-namespace/backup_test.go
  systest/backup/advanced-scenarios/deleted-namespace/docker-compose.yml
Labels: area/testing, area/graphql, area/core, go

#8686 chor(changelog): add changelog for v23.0.0-beta
  CHANGELOG.md
Labels: area/documentation, v23.0.0-beta

#8713 fix(changelog): update release version
  CHANGELOG.md
Labels: area/documentation

#8716 chore(ci): resolve community PR goveralls failure
  .github/workflows/ci-dgraph-code-coverage.yml
Labels: area/integrations

#8698 chore(cd): add cd workflow to slash branch
  .github/workflows/cd-dgraph.yml
  .go-version
  Makefile
  dgraph/Makefile
  graphql/e2e/custom_logic/cmd/Dockerfile
Labels: area/integrations

#8711 chore(test):Increased iterations of the health check of the container
  testutil/docker.go
Labels: area/testing, go

#8718 chore(linter): fix unconvert linter issues on linux
  x/disk_metrics_linux.go
Labels: area/core, go

#8725 release filter for load test
  .github/workflows/ci-dgraph-load-tests.yml
Labels: area/integrations

#8719 fix: check index for next word and replace global index with local one
  Makefile
  chunker/json_parser.go
  codec/benchmark/benchmark.go
  codec/codec.go
  contrib/integration/swap/main.go
  contrib/integration/swap/words.go
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/live/batch.go
  dgraph/cmd/live/run.go
  dgraph/cmd/migrate/datatype.go
  dgraph/cmd/zero/zero.go
  dgraph/cmd/zero/zero_test.go
  graphql/authorization/auth.go
  paper/dgraph.tex
  raftwal/meta.go
  tok/tok.go
  types/scalar_types.go
  x/keys.go
  x/log_writer.go
Labels: area/testing, area/documentation, area/graphql, area/integrations, area/bulk-loader, area/live-loader, area/core, go

#8722 chore(changelog): fix broken link
  CHANGELOG.md
Labels: area/documentation

#8733 contrib: stop exposing only Alpha ports in docker image
  contrib/Dockerfile
Labels: area/integrations

#8707 chore(test): add layout for dgraphtest package
  dgraphtest/config.go
  dgraphtest/data/enc-key
  dgraphtest/data/hmac-secret
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  go.mod
Labels: go

#8731 chore: remove unused functions in x and replace panic with x.Panic
  chunker/json_parser.go
  codec/benchmark/benchmark.go
  dgraph/cmd/alpha/run_test.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/live/run.go
  dgraph/cmd/root.go
  graphql/bench/auth_test.go
  graphql/e2e/auth/auth_test.go
  graphql/e2e/auth/debug_off/debugoff_test.go
  graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
  graphql/e2e/common/admin.go
  graphql/e2e/common/common.go
  graphql/e2e/normal/normal_test.go
  graphql/resolve/resolver_error_test.go
  query/outputnode.go
  query/outputnode_test.go
  systest/bgindex/count_test.go
  types/facets/facet_types.go
  worker/queue.go
  x/config.go
  x/file.go
  x/init.go
  x/keys.go
  x/log.go
  x/server.go
  x/x.go
Labels: area/testing, area/graphql, area/bulk-loader, area/live-loader, area/core, go

#8734 chore(test): use pointer receiver for LocalCluster methods
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
Labels: go

#8737 feat(metrics): add badger metrics (#8034)
  dgraph/cmd/alpha/metrics_test.go
  x/metrics.go
Labels: area/testing, dgraph, area/core, go

#8745 fix(tests): sleep longer so that ACLs are updated
  ee/acl/acl_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, go

#8741 Add Upgrade and setup binaries function
  dgraphtest/.gitignore
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  dgraphtest/paths.go
  go.mod
  go.sum
Labels: go

#8744 fix(tests): wait for license to be applied before trying to login
  systest/backup/advanced-scenarios/deleted-namespace/docker-compose.yml
  testutil/docker.go
Labels: area/testing, go

#8739 fix(dql): fix panic in parsing of regexp
  dql/parser.go
  query/query0_test.go
  systest/mutations_test.go
Labels: area/testing, area/querylang, area/core, go

#8726 chore(tests): run tests in query package against dgraph cloud
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/config.go
  dgraphtest/dcloud_cluster.go
  dgraphtest/dgraph.go
  dgraphtest/local_cluster.go
  go.mod
  go.sum
  query/cloud_test.go
  query/common_test.go
  query/integration_test.go
  query/mutation_test.go
  query/query0_test.go
  query/query1_test.go
  query/query2_test.go
  query/query3_test.go
  query/query4_test.go
  query/query_facets_test.go
  query/rdf_result_test.go
Labels: dgraph

#8740 chore(worker): unify mapper receiver names
  worker/acl_cache.go
  worker/aggregator.go
  worker/backup.go
  worker/backup_ee.go
  worker/backup_handler.go
  worker/backup_manifest.go
  worker/backup_oss.go
  worker/compare.go
  worker/draft.go
  worker/groups.go
  worker/match.go
  worker/restore_map.go
  worker/sort.go
Labels: area/core, go

#8749 chore: fix linter issue on main
  worker/compare.go
Labels: area/core, go

#8696 docs(RFC): Add RFC template, folders and readme
  RFC/Deprecated/readme.md
  RFC/Post-mortem/readme.md
  RFC/Proposals/readme.md
  RFC/readme.md
  RFC/template.md
Labels: area/documentation, dgraph, area/RFC

#8753 chore(test):Add build tag to newly added tests
  systest/backup/advanced-scenarios/127-Namespace/backup_test.go
  systest/backup/advanced-scenarios/acl-nonAcl/backup_test.go
  systest/backup/advanced-scenarios/deleted-namespace/backup_test.go
Labels: area/testing, go

#8727 chore(debug): Add VSCode config file for debugging.
  .gitignore
  .vscode/launch.json
Labels: dgraph

#8762 chore(docs): fix local-test cluster makefile
  contrib/local-test/Makefile
Labels: area/integrations

#8760 fix(cve): resolve cve's in slash
  .github/workflows/ci-aqua-security-trivy-tests.yml
  go.mod
  go.sum
Labels: area/testing, area/enterprise, area/schema, area/graphql, area/integrations, area/bulk-loader, area/live-loader, area/enterprise/acl, area/enterprise/backup, area/core, go

#8761 chore: clean up unused files + dependencies
  .codeclimate.yml
  .deepsource.toml
  .travis.yml
  .travis/ratel.enc
  contrib/release.sh
  contrib/release/xgo.Dockerfile
  contrib/update-badger.sh
  go.mod
  go.sum
  netlify.toml
  tools.go
Labels: area/integrations, go

#8763 dgraphtest: improve logging and health check
  dgraphtest/cluster.go
  dgraphtest/compose_cluster.go
  dgraphtest/config.go
  dgraphtest/dcloud_cluster.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
Labels: go

#8765 chore(tests): avoid calling os.Exit in TestMain
  dgraph/cmd/live/load-json/load_test.go
  dgraph/cmd/live/load-uids/load_test.go
  dql/parser_test.go
  ee/acl/acl_test.go
  graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
  graphql/e2e/custom_logic/custom_logic_test.go
  graphql/e2e/directives/dgraph_directives_test.go
  graphql/e2e/normal/normal_test.go
  graphql/e2e/schema/schema_test.go
  graphql/e2e/subscription/subscription_test.go
  graphql/schema/schemagen_test.go
  systest/backup/advanced-scenarios/127-Namespace/backup_test.go
  systest/multi-tenancy/basic_test.go
  worker/worker_test.go
  x/error_test.go
Labels: area/testing, area/enterprise, area/querylang, area/graphql, area/live-loader, area/enterprise/acl, area/core, go

#8348 fix(test): Clean cruft from test run
  edgraph/server_test.go
Labels: dgraph

#8772 use testing.T.TempDir() for temp dir in tests
  conn/node_test.go
  dgraph/cmd/live/load-json/load_test.go
  dgraph/cmd/live/load-uids/load_test.go
  dgraph/cmd/version/version_test.go
  dql/parser_test.go
  edgraph/server_test.go
  ee/acl/acl_test.go
  graphql/e2e/auth_closed_by_default/auth_closed_by_default_test.go
  graphql/e2e/custom_logic/custom_logic_test.go
  graphql/e2e/directives/dgraph_directives_test.go
  graphql/e2e/normal/normal_test.go
  graphql/e2e/schema/schema_test.go
  graphql/e2e/subscription/subscription_test.go
  graphql/schema/schemagen_test.go
  posting/list_test.go
  posting/writer_test.go
  query/cloud_test.go
  query/integration_test.go
  raftwal/encryption_test.go
  raftwal/storage_test.go
  schema/parse_test.go
  systest/loader/loader_test.go
  systest/multi-tenancy/basic_test.go
  worker/draft_test.go
  worker/export_test.go
  worker/worker_test.go
  x/error_test.go
  xidmap/xidmap_test.go
Labels: area/testing, area/enterprise, area/querylang, area/schema, area/graphql, area/live-loader, area/enterprise/acl, area/core, go

#8769 fix(Query): Do an error check before bubbling up nil error
  query/query.go
  query/query0_test.go
Labels: area/core, go

#8775 fix the backup test cluster
  systest/backup/nfs-backup/docker-compose.yml
Labels: area/testing
