Repository hypermodeinc/dgraph, pull requests merged in 2024-08, with the labels that each got.

#9124 Update CHANGELOG.md to add 24.0.1
  CHANGELOG.md
Labels: area/documentation

#9126 fix(core): Fix regression in computing cond variables
  graphql/e2e/schema/schema_test.go
  query/common_test.go
  query/query.go
  query/query0_test.go
  testutil/docker.go
Labels: area/core, go

#9121 fix(live): Fix derigster while retrying
  dgraph/cmd/live/batch.go
  graphql/e2e/schema/schema_test.go
  systest/loader/loader_test.go
  testutil/client.go
  testutil/docker.go
  tlstest/certrequest/certrequest_test.go
  tlstest/certrequireandverify/certrequireandverify_test.go
  tlstest/certverifyifgiven/certverifyifgiven_test.go
Labels: area/live-loader, go

#8966 perf(query): Read just the latest value for scalar types
  posting/list.go
  posting/list_test.go
  posting/lists.go
  worker/task.go
Labels: area/testing, area/core, go

#9122 perf(vector): Add heap to neighbour edges
  posting/index.go
  posting/list.go
  posting/lists.go
  posting/oracle.go
  query/math.go
  query/math_test.go
  query/query.go
  query/vector/vector_test.go
  tok/hnsw/heap.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_factory.go
  tok/hnsw/persistent_hnsw.go
  tok/hnsw/persistent_hnsw_test.go
  tok/hnsw/search_layer.go
  tok/hnsw/test_helper.go
  tok/index/helper.go
  tok/index/helper_test.go
  tok/index/index.go
  tok/index/search_path.go
  tok/index/types.go
Labels: area/core, go

#9128 Add 24.0.2 to CHANGELOG.md
  CHANGELOG.md
Labels: area/documentation

#3981 Adds support for BigFloat
  chunker/rdf_parser.go
  dgraph/cmd/alpha/upsert_test.go
  dql/mutation.go
  edgraph/server.go
  go.mod
  go.sum
  protos/pb.proto
  protos/pb/pb.pb.go
  query/aggregator.go
  query/math_test.go
  query/outputnode.go
  query/query4_test.go
  schema/parse_test.go
  tok/tok.go
  types/conversion.go
  types/scalar_types.go
  types/sort.go
  worker/export.go
Labels: dgraph

#9130 fix(tests): add explicit permissions for Trivy scan
  .github/workflows/ci-aqua-security-trivy-tests.yml
Labels: area/integrations

#9132 chore(): add Dependabot version bumps
  .github/dependabot.yml
Labels: area/integrations

#9148 fix(git): fix Labeler formatting
  .github/labeler.yml
  .github/workflows/labeler.yml
Labels: area/integrations

#9149 fix(vector): fix index rebuild when options change
  posting/index.go
  query/vector/vector_graphql_test.go
  query/vector/vector_test.go
  tok/hnsw/persistent_factory.go
Labels: area/testing, area/core, go
