Repository hypermodeinc/dgraph, pull requests merged in 2024-10, with the labels that each got.

#9181 fix(core): add the posting list risteretto cache back
  ee/acl/acl_test.go
  go.mod
  go.sum
  posting/lists.go
  posting/mvcc.go
Labels: area/testing, area/enterprise, area/enterprise/acl, area/core, go

#9196 fix(core): fix performance impact in mutation due to vector
  posting/index.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9201 fix unique query for non-latin predicate name and whitespace in query
  edgraph/server.go
  systest/unique_test.go
Labels: area/testing, go

#9202 Enhancing Dgraph cd pipeline to only push images to Dockerhub when both AMD and ARM builds are successful
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#9205 Adding 24.0.4 to CHANGELOG.md
  CHANGELOG.md
Labels: area/documentation

#9207 Update cd-dgraph.yml to avoid conflict during artifact upload
  .github/workflows/cd-dgraph.yml
Labels: area/integrations
