Repository hypermodeinc/dgraph, pull requests merged in 2024-05, with the labels that each got.

#9078 fix(restore): fix incr restore and normal restore for vector predicates
  systest/vector/backup_test.go
  worker/backup_ee.go
  worker/restore_map.go
Labels: area/testing, go

#9084 fix(vector):fix similar_to() error return when data is not present
  query/vector/vector_test.go
  systest/vector/vector_test.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_hnsw.go
  worker/task.go
Labels: area/testing, area/core, go

#9089 perf(core): Fix performance issue in type filter (#9065)
  dgraph/cmd/alpha/run.go
  posting/list.go
  systest/backup/encryption/backup_test.go
  worker/config.go
  worker/draft.go
  worker/server_state.go
  worker/task.go
Labels: area/testing, area/core, go

#9083 fix(vector): Update query_rewriter to fix dotproduct and cosine query conversion
  graphql/resolve/query_rewriter.go
  graphql/resolve/query_test.yaml
  query/vector/vector_graphql_test.go
Labels: area/graphql, area/core, go

#9088 Perf(core): Update postinglistCountAndLength function to improve performance
  posting/index.go
  posting/list.go
Labels: area/core, go

#9085 Fix(core): Fix deadlock in runMutation and error handling
  posting/mvcc.go
  query/vector/vector_test.go
  systest/vector/backup_test.go
  tok/hnsw/helper.go
  worker/draft.go
  worker/mutation.go
Labels: area/core, go

#9068 feat(core): Add cache to dgraph.type predicate.
  posting/index.go
  posting/list.go
  posting/list_test.go
  posting/lists.go
  posting/mvcc.go
  posting/mvcc_test.go
  posting/oracle.go
  worker/draft.go
  worker/server_state.go
  worker/snapshot.go
  x/keys.go
Labels: area/testing, area/core, go

#9092 Enhancing CD pipeline to add ability for pushing to a dgraph-custom repo
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#9093 Fixing issue with if condition while pushing manifest for the cd pipeline
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#9094 Editing upgrade CI jobs to run at 11am so that we can debug if there are execution issues
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
Labels: area/integrations

#9096 Github Actions cron time is in UTC, adjusting to 12:30 PST to get run at the earliest
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
Labels: area/integrations

#9098 Fixing cd-dgraph.yml to tag custom build correctly
  .github/workflows/cd-dgraph.yml
Labels: area/integrations
