Repository hypermodeinc/dgraph, pull requests merged in 2024-09, with the labels that each got.

#9159 fix(multi-tenancy): upsert groot for namespace after drop data
  edgraph/server.go
  systest/multi-tenancy/login_test.go
Labels: area/testing, area/graphql, area/core, go

#9165 fix(vector): fixed euclidean spelling and a bug in parameters
  graphql/resolve/query_rewriter.go
  graphql/schema/dgraph_schemagen_test.yml
  graphql/schema/rules.go
  graphql/schema/testdata/schemagen/input/embedding-directive-with-similar-queries.graphql
  graphql/schema/testdata/schemagen/output/embedding-directive-with-similar-queries.graphql
  graphql/schema/wrappers.go
  query/common_test.go
  query/vector/vector_graphql_test.go
  query/vector/vector_test.go
  schema/parse_test.go
  systest/vector/vector_test.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_factory.go
  tok/hnsw/persistent_hnsw.go
  tok/hnsw/persistent_hnsw_test.go
  tok/options/README.md
  worker/worker_test.go
Labels: area/testing, area/documentation, area/schema, area/graphql, area/core, go

#9169 fix(core): update latest badger
  go.mod
  go.sum
  posting/lists.go
  posting/mvcc.go
Labels: area/core, go

#9170 fix(core): Update error msg for txn too old to give more context
  posting/index.go
  posting/list.go
  posting/mvcc.go
  worker/task.go
Labels: area/core, go

#9175 Update README.md
  README.md
Labels: area/documentation

#9173 fix(DQL): unsupported ordering should raise an error
  dql/parser.go
  ee/acl/acl_test.go
  query/query4_test.go
Labels: area/testing, area/enterprise, area/querylang, area/enterprise/acl, area/core, go

#9177 update expired certificate that are used for testing
  tlstest/mtls_internal/tls/alpha1/client.alpha1.crt
  tlstest/mtls_internal/tls/alpha1/client.alpha1.key
  tlstest/mtls_internal/tls/alpha1/node.crt
  tlstest/mtls_internal/tls/alpha1/node.key
  tlstest/mtls_internal/tls/alpha2/client.alpha2.crt
  tlstest/mtls_internal/tls/alpha2/client.alpha2.key
  tlstest/mtls_internal/tls/alpha2/node.crt
  tlstest/mtls_internal/tls/alpha2/node.key
  tlstest/mtls_internal/tls/alpha3/client.alpha3.crt
  tlstest/mtls_internal/tls/alpha3/client.alpha3.key
  tlstest/mtls_internal/tls/alpha3/node.crt
  tlstest/mtls_internal/tls/alpha3/node.key
  tlstest/mtls_internal/tls/alpha4/client.alpha4.crt
  tlstest/mtls_internal/tls/alpha4/client.alpha4.key
  tlstest/mtls_internal/tls/alpha4/node.crt
  tlstest/mtls_internal/tls/alpha4/node.key
  tlstest/mtls_internal/tls/alpha5/client.alpha5.crt
  tlstest/mtls_internal/tls/alpha5/client.alpha5.key
  tlstest/mtls_internal/tls/alpha5/node.crt
  tlstest/mtls_internal/tls/alpha5/node.key
  tlstest/mtls_internal/tls/alpha6/client.alpha6.crt
  tlstest/mtls_internal/tls/alpha6/client.alpha6.key
  tlstest/mtls_internal/tls/alpha6/node.crt
  tlstest/mtls_internal/tls/alpha6/node.key
  tlstest/mtls_internal/tls/live/client.liveclient.crt
  tlstest/mtls_internal/tls/live/client.liveclient.key
  tlstest/mtls_internal/tls/zero1/client.zero1.crt
  tlstest/mtls_internal/tls/zero1/client.zero1.key
  tlstest/mtls_internal/tls/zero1/node.crt
  tlstest/mtls_internal/tls/zero1/node.key
  tlstest/mtls_internal/tls/zero2/client.zero2.crt
  tlstest/mtls_internal/tls/zero2/client.zero2.key
  tlstest/mtls_internal/tls/zero2/node.crt
  tlstest/mtls_internal/tls/zero2/node.key
  tlstest/mtls_internal/tls/zero3/client.zero3.crt
  tlstest/mtls_internal/tls/zero3/client.zero3.key
  tlstest/mtls_internal/tls/zero3/node.crt
  tlstest/mtls_internal/tls/zero3/node.key
Labels: area/testing

#9176 Expose APIs that can be used outside Dgraph
  edgraph/server.go
  query/mutation.go
  worker/server_state.go
Labels: area/testing, area/core, go
