Repository hypermodeinc/dgraph, pull requests merged in 2024-12, with the labels that each got.

#9230 fix(core): fix batching of running mutations in one transaction
  go.mod
  worker/draft.go
  worker/worker_test.go
Labels: area/testing, area/core, go

#9216 expose function to Query without auth
  edgraph/server.go
  worker/embedded.go
Labels: area/core, go

#9199 perf(core): Introduce mutable map struct
  dgraph/cmd/debug/run.go
  posting/index.go
  posting/index_test.go
  posting/list.go
  posting/list_test.go
  posting/mvcc.go
  posting/mvcc_test.go
  posting/size.go
  posting/size_test.go
  systest/mutations-and-queries/mutations_test.go
  tok/hnsw/helper.go
  worker/mutation_unit_test.go
  worker/sort_test.go
  worker/worker_test.go
  x/debug.go
Labels: area/testing, area/core, go

#9235 check for error in vector hnsw code
  tok/hnsw/persistent_hnsw.go
Labels: go

#9238 fix the unique constraint when adding two mutations in a single request
  edgraph/server.go
  systest/unique_test.go
Labels: area/testing, go

#9214 Add index after adding data without vector schema for vector predicate
  chunker/json_parser_test.go
  dgraphapi/vector.go
  posting/index.go
  systest/vector/backup_test.go
  systest/vector/load_test.go
  systest/vector/vector_test.go
Labels: area/testing, area/core, go

#9243 ci: separate CI workflows
  .github/workflows/ci-dgraph-core-tests.yml
  .github/workflows/ci-dgraph-core-upgrade-tests.yml
  .github/workflows/ci-dgraph-system-upgrade-tests.yml
  .github/workflows/ci-dgraph-systest-tests.yml
  .github/workflows/ci-dgraph-vector-tests.yml
  t/t.go
Labels: area/testing, area/integrations, go

#9245 ci(test): integrate Trunk into multiple CI workflows to identify flaky tests
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-core-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-systest-tests.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-vector-tests.yml
  t/t.go
Labels: area/testing, area/integrations, go
