Repository hypermodeinc/dgraph, pull requests merged in 2024-07, with the labels that each got.

#9112 Chore(): create stale.yml
  .github/workflows/stale.yml
Labels: area/integrations

#9081 chore(changelog): update changelog for v23.1.1
  CHANGELOG.md
Labels: area/documentation, Stale

#9080 chore(changelog): update changelog for v23.1.1
  CHANGELOG.md
Labels: area/documentation, Stale

#9042 fix(upgrade): fix failing upgrade tests
  dgraphtest/config.go
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  ee/acl/upgrade_test.go
  go.mod
  query/common_test.go
  query/rdf_result_test.go
  systest/multi-tenancy/upgrade_test.go
Labels: area/testing, area/core, go, Stale

#9116 fix(ci): fixing health endpoint issue
  dgraphtest/dgraph.go
  dgraphtest/local_cluster.go
Labels: go

#9114 Fix(graphql): issue with local variable squashing intended JWK index
  graphql/authorization/auth.go
Labels: area/graphql, area/core, go

#9109 perf(vector): updated marshalling of vector
  dgraphtest/config.go
  dgraphtest/local_cluster.go
  go.mod
  go.sum
  posting/index.go
  posting/lists.go
  posting/mvcc.go
  query/vector/vector_test.go
  tok/hnsw/heap.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_hnsw.go
  tok/hnsw/persistent_hnsw_test.go
  tok/hnsw/search_layer.go
  tok/index/helper.go
  tok/index/helper_test.go
  worker/task.go
Labels: area/testing, area/core, go

#9119 fix(core): Fix namespace used by unique query generator
  edgraph/server.go
  ee/acl/acl_integration_test.go
Labels: area/testing, area/enterprise, area/enterprise/acl, go
