Repository hypermodeinc/dgraph, pull requests merged in 2024-11, with the labels that each got.

#9208 fix(core): fix duplicate mutation entries for count index
  dgraph/cmd/debug/run.go
  posting/index.go
  posting/list.go
  posting/mvcc.go
  protos/pb.proto
  protos/pb/pb.pb.go
  worker/mutation.go
  worker/mutation_unit_test.go
  worker/upgrade_test.go
  worker/worker_test.go
Labels: area/testing, area/core, go

#9206 fix(export): delete temporary export directory after completion of remote export
  worker/export.go
Labels: area/core, go

#9209 fix(core): fix duplicate mutation entries for count index (#9208)
  dgraph/cmd/debug/run.go
  posting/index.go
  posting/list.go
  posting/mvcc.go
  protos/pb.proto
  protos/pb/pb.pb.go
  worker/mutation.go
  worker/mutation_unit_test.go
  worker/upgrade_test.go
  worker/worker_test.go
Labels: area/testing, area/core, go

#9222 Megha/cd pipeline enhancement
  .github/workflows/cd-dgraph.yml
Labels: area/integrations

#9224 Fixing README.md to mention 24.0.5 as latest also fixing wrong link
  README.md
Labels: area/documentation

#9221 fix(core): fix visited uids bitset memory
  tok/hnsw/persistent_hnsw.go
Labels: go

#9226 fix(core): fix visited uids bitset memory (#9221)
  tok/hnsw/persistent_hnsw.go
Labels: go
