Repository hypermodeinc/dgraph, pull requests merged in 2024-04, with the labels that each got.

#9060 feat(vector): add vector to schema
  go.mod
  go.sum
  schema/parse.go
  schema/parse_test.go
  schema/schema.go
  schema/state.go
  tok/constraints/constraints.go
  tok/hnsw/heap.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_factory.go
  tok/hnsw/persistent_hnsw.go
  tok/index/index.go
  tok/index/types.go
  tok/index_factory.go
  tok/options/README.md
  tok/options/allowed_options.go
  tok/options/option_parser.go
  tok/options/options.go
  tok/options/options_test.go
  tok/tok.go
  worker/mutation.go
  worker/schema.go
  worker/worker_test.go
Labels: area/testing, area/documentation, area/schema, area/core, go

#9063 fix live loader and add tests for dropall, drop namespace, live load
  chunker/rdf_parser.go
  dgraphtest/cluster.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  dgraphtest/vector.go
  dql/parser.go
  protos/pb.proto
  protos/pb/pb.pb.go
  query/vector_test.go
  systest/vector/load_test.go
  systest/vector/vector_test.go
  worker/export.go
  worker/schema.go
  worker/worker_test.go
Labels: area/testing, area/core, go

#9064 fix(vector): Show error is invalid input is provided to vector predicate
  query/vector_test.go
  worker/mutation.go
Labels: area/testing, area/core, go

#9069 Cherry-pick of https://github.com/dgraph-io/dgraph/pull/9054 to release/v23.1 branch
  .github/workflows/cd-dgraph.yml
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-integration2-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  .github/workflows/ci-golang-lint.yml
  contrib/Dockerfile
Labels: area/integrations

#9066 chore: remove repetitive words
  graphql/resolve/update_mutation_test.yaml
  query/query3_test.go
  systest/mutations-and-queries/mutations_test.go
Labels: area/testing, area/graphql, area/core, go

#9071 ci(build): add nightly Trivy scan
  .github/workflows/ci-aqua-security-trivy-tests.yml
Labels: area/integrations

#9073 ci(build): enable CodeQL scanning
  .github/workflows/codeql.yml
Labels: area/integrations

#9076 Fix(debug): Close file correctly before exiting on error
  dgraph/cmd/debuginfo/debugging.go
Labels: go
