Repository hypermodeinc/dgraph, pull requests merged in 2024-03, with the labels that each got.

#9046 ci(upgrade):enable upgrade workflow on PR
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  dgraphtest/local_cluster.go
Labels: area/integrations

#9043 fix(query): fix has function in filter
  query/query0_test.go
  worker/task.go
Labels: area/testing, area/core, go

#9047 Reduce x.ParsedKey memory allocation from 72 to 56 bytes by optimizing struct memory alignment
  x/keys.go
Labels: area/core, go

#9044 Remove embargo
  contrib/embargo/.gitignore
  contrib/embargo/.python-version
  contrib/embargo/embargo.yml
  contrib/embargo/main.go
  contrib/embargo/requirements.txt
  contrib/embargo/run.sh
Labels: area/integrations, go

#9017 fix(restore): do not retry restore proposal (#8058)
  worker/online_restore.go
Labels: area/core, go

#9038 refactor(dql): Split mutation test
  worker/mutation_integration_test.go
  worker/mutation_unit_test.go
Labels: area/testing, area/core, go

#9011 chore(ci): typo in cron
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#9039 chore: fix CI issues
  .github/workflows/cd-dgraph.yml
  edgraph/server.go
  systest/acl/restore/acl_restore_test.go
Labels: area/testing, area/integrations, go

#8935 chore(ci): add jepsen test workflow
  .github/workflows/ci-dgraph-jepsen-tests.yml
Labels: area/integrations

#9052 Optimize CI Workflows
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations

#9007 Fixed deadlock that happens due to timeout
  worker/proposal.go
Labels: area/core, go

#9040 ci: wait for the cluster to startup in tlstest
  tlstest/certrequest/certrequest_test.go
Labels: area/testing, go

#9010 alpha: limit #edges using LimitMutationsNquad config and add logs
  edgraph/server.go
  go.mod
  query/shortest.go
  worker/proposal.go
Labels: area/testing, area/core, go

#9009 debug: fix debug tool to read WAL entries correctly
  dgraph/cmd/debug/run.go
  dgraph/cmd/debug/wal.go
  go.mod
  go.sum
Labels: go

#9054 ci/cd optimizations
  .github/workflows/cd-dgraph.yml
  .github/workflows/ci-aqua-security-trivy-tests.yml
  .github/workflows/ci-dgraph-code-coverage.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-integration2-tests.yml
  .github/workflows/ci-dgraph-jepsen-tests.yml
  .github/workflows/ci-dgraph-ldbc-tests.yml
  .github/workflows/ci-dgraph-load-tests.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-tests-arm64.yml
  .github/workflows/ci-dgraph-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .github/workflows/ci-dgraph-upgrade-tests.yml
  .github/workflows/ci-golang-lint.yml
  contrib/Dockerfile
Labels: area/integrations

#9050 Add vector type to Dgraph
  chunker/json_parser.go
  dql/mutation.go
  go.mod
  go.sum
  graphql/e2e/common/error_test.yaml
  graphql/resolve/validate_mutation_test.yaml
  protos/pb.proto
  protos/pb/pb.pb.go
  query/aggregator.go
  query/common_test.go
  query/math.go
  query/math_test.go
  query/outputnode.go
  query/query.go
  query/query0_test.go
  schema/parse_test.go
  tlstest/certrequireandverify/certrequireandverify_test.go
  types/conversion.go
  types/conversion_test.go
  types/scalar_types.go
  types/value.go
  types/value_test.go
  worker/aggregator.go
Labels: area/testing, area/querylang, area/schema, area/core, go

#9058 upgrade(go): update go version to 1.22
  .go-version
  contrib/local-test/Makefile
  dgraphtest/config.go
  dgraphtest/dgraph.go
  go.mod
  go.sum
  graphql/e2e/common/error_test.yaml
  graphql/resolve/validate_mutation_test.yaml
  graphql/schema/rules.go
  systest/1million/test-reindex.sh
  systest/21million/test-21million.sh
  systest/integration2/graphql_schema_auth_test.go
  systest/loader-benchmark/loader-benchmark.sh
  t/t.go
  testutil/bulk.go
Labels: area/testing, area/graphql, area/core, go

#9059 Update ci-golang-lint.yml
  .github/workflows/ci-golang-lint.yml
Labels: area/integrations
