Repository hypermodeinc/dgraph, pull requests merged in 2025-02, with the labels that each got.

#9299 perf(core): Use Intersect to Narrow Iterate Range and Reduce Memory Allocation in pl.Uids()
  posting/list.go
Labels: area/core, go

#9301 Reduce memory usage during Alter execution
  worker/mutation.go
Labels: area/core, go

#9303 chore: bump Go patch version
  .trunk/trunk.yaml
  CONTRIBUTING.md
  go.mod
  graphql/e2e/custom_logic/cmd/go.mod
  t/Makefile
  t/README.md
Labels: area/testing, area/documentation, area/graphql, area/core

#9250 Refactor test code
  chunker/json_parser_test.go
  contrib/integration/testtxn/main_test.go
  dgraph/cmd/alpha/http_test.go
  dgraph/cmd/alpha/run_test.go
  dgraph/cmd/alpha/upsert_test.go
  dgraphapi/schema.go
  dgraphtest/local_cluster.go
Labels: area/testing, area/integrations, go

#9302 bump Ubuntu to v24.04
  contrib/Dockerfile
Labels: area/integrations

#9287 perf(vector): Improve how vector is passed to hnsw index
  posting/list.go
  posting/lists.go
  posting/oracle.go
  tok/hnsw/helper.go
  tok/hnsw/persistent_hnsw.go
  tok/hnsw/persistent_hnsw_test.go
  tok/hnsw/test_helper.go
  tok/index/index.go
Labels: area/testing, area/core, go

#9305 chore: update benchmark paths
  CHANGELOG.md
  algo/benchmarks
  chunker/README.txt
  contrib/manual_tests/test.sh
  graphql/bench/README.md
  graphql/testdata/custom_bench/profiling/graphql_profiler.go
  paper/dgraph.tex
  systest/1million/test-reindex.sh
  systest/21million/test-21million.sh
  systest/loader-benchmark/loader-benchmark.sh
  t/t.go
Labels: area/testing, area/documentation, area/graphql, area/integrations, area/core, go

#9307 chore(deps): bump Go patch version
  .trunk/trunk.yaml
  CONTRIBUTING.md
  SECURITY.md
  go.mod
  graphql/e2e/custom_logic/cmd/go.mod
  t/Makefile
  t/README.md
Labels: area/testing, area/documentation, area/graphql, area/core

#9252 add grpc API for creating/deleting/rename/listing namespaces
  dgraph/cmd/alpha/run.go
  dgraphapi/schema.go
  dgraphtest/compose_cluster.go
  dgraphtest/image.go
  dgraphtest/paths.go
  edgraph/access_ee.go
  edgraph/multi_tenancy.go
  edgraph/multi_tenancy_ee.go
  edgraph/namespace.go
  edgraph/namespace_test.go
  edgraph/server.go
  go.mod
  go.sum
  graphql/admin/namespace.go
  posting/mvcc.go
  testutil/client.go
Labels: area/testing, area/schema, area/graphql, area/core, go

#9313 Add Dockerfile and cd for pushing nightly docker images
  .dockerignore
  .github/workflows/cd-dgraph-nightly.yml
  .github/workflows/cd-dgraph.yml
  .github/workflows/ci-dgraph-systest-tests.yml
  .trunk/configs/.checkov.yaml
  .trunk/configs/.trivyignore.yaml
  .trunk/trunk.yaml
  Dockerfile
Labels: area/integrations

#9328 upgrade go version to v1.23.6 from v1.22.12
  .trunk/trunk.yaml
  Dockerfile
  go.mod
  go.sum
  graphql/e2e/custom_logic/cmd/go.mod
  t/Makefile
  types/scalar_types.go
  types/scalar_types_test.go
Labels: area/testing, area/graphql, area/core, go
