Repository hypermodeinc/dgraph, pull requests merged in 2025-05, with the labels that each got.

#9404 update URLs to download data from dgraph-benchmarks repo
  t/t.go
Labels: area/testing, go

#9381 feat: add import api support for multiple groups with a single alphas
  check_upgrade/check_upgrade_test.go
  dgraph/cmd/alpha/run_test.go
  dgraph/cmd/dgraphimport/import_client.go
  dgraph/cmd/dgraphimport/import_test.go
  dgraphtest/.gitignore
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  dgraphtest/paths.go
  edgraph/server.go
  go.mod
  go.sum
  protos/Makefile
  protos/pb.proto
  protos/pb/pb.pb.go
  protos/pb/pb_grpc.pb.go
  worker/draft.go
  worker/import.go
Labels: area/testing, area/bulk-loader, area/core, go

#9400 Add implementation for AllocateIDs and use the API in live loader
  dgraph/cmd/live/batch.go
  dgraph/cmd/live/load-json/load_test.go
  dgraph/cmd/live/load-uids/load_test.go
  dgraph/cmd/live/run.go
  dgraph/cmd/zero/zero_test.go
  edgraph/zero.go
  go.mod
  go.sum
  query/normalize_feature_flag_test.go
  systest/21million/live/run_test.go
  systest/bgindex/count_test.go
  systest/bgindex/parallel_test.go
  systest/bgindex/reverse_test.go
  systest/bgindex/string_test.go
  systest/bulk_live/common/bulk_live_fixture.go
  systest/integration2/incremental_restore_test.go
  systest/multi-tenancy/integration_basic_helper_test.go
  testutil/bulk.go
  worker/mutation.go
  worker/upgrade_test.go
  xidmap/xidmap.go
Labels: area/testing, area/graphql, area/live-loader, area/acl, area/core, go
