Repository hypermodeinc/dgraph, pull requests merged in 2025-03, with the labels that each got.

#9319 fix(core): change delete-on-updates to remove-on-update and set default false
  dgraph/cmd/alpha/run.go
  posting/index.go
  posting/lists.go
  posting/mvcc.go
  worker/config.go
  worker/server_state.go
Labels: area/testing, area/integrations, area/core, go

#9329 fix(core):change delete-on-update to remove-on-update and set default
  .github/renovate.json
  .github/workflows/cd-dgraph.yml
  .github/workflows/ci-dgraph-core-upgrade-tests.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-jepsen-tests.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-system-upgrade-tests.yml
  .github/workflows/ci-dgraph-systest-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  .trunk/trunk.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  SECURITY.md
  algo/benchmarks
  chunker/README.txt
  contrib/manual_tests/test.sh
  dgraph/cmd/alpha/run.go
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  dgraphtest/paths.go
  ee/acl/acl_test.go
  ee/acl/upgrade_test.go
  go.mod
  go.sum
  graphql/bench/README.md
  graphql/e2e/custom_logic/cmd/go.mod
  graphql/testdata/custom_bench/profiling/graphql_profiler.go
  paper/dgraph.tex
  posting/index.go
  posting/lists.go
  posting/mvcc.go
  query/upgrade_test.go
  systest/1million/test-reindex.sh
  systest/21million/test-21million.sh
  systest/loader-benchmark/loader-benchmark.sh
  t/Makefile
  t/README.md
  t/t.go
  worker/config.go
  worker/server_state.go
Labels: area/testing, area/documentation, area/enterprise, area/graphql, area/integrations, area/enterprise/acl, area/core, go

#9314 Implement Alter with v25 namespaces
  .trunk/trunk.yaml
  dgraph/cmd/alpha/run.go
  edgraph/alter.go
  edgraph/alter_test.go
  edgraph/multi_tenancy.go
  edgraph/namespace.go
  edgraph/namespace_test.go
  edgraph/server.go
  edgraph/server_test.go
  go.mod
  go.sum
  posting/index.go
  protos/pb.proto
  protos/pb/pb.pb.go
  worker/draft.go
Labels: area/testing, area/enterprise, area/graphql, area/integrations, area/live-loader, area/enterprise/acl, area/core, go

#9336 Update changelog for v24.1.0
  CHANGELOG.md
Labels: area/documentation

#9337 fix(core): put new metrics behind a feature flag
  dgraph/cmd/alpha/run.go
  posting/lists.go
  posting/mvcc.go
  worker/server_state.go
Labels: area/core, go

#9345 remove depecrated code used from grpc library
  conn/pool.go
  dgraph/cmd/alpha/mutations_mode/mutations_mode_test.go
  dgraph/cmd/bulk/loader.go
  dgraph/cmd/zero/zero_test.go
  dgraphtest/local_cluster.go
  ee/backup/run.go
  graphql/e2e/common/admin.go
  graphql/e2e/common/common.go
  graphql/e2e/common/error.go
  graphql/e2e/common/mutation.go
  graphql/e2e/common/query.go
  graphql/e2e/common/schema.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio-large/backup_test.go
  systest/backup/minio/backup_test.go
  systest/backup/nfs-backup/backup_test.go
  systest/export/export_test.go
  systest/online-restore/online_restore_test.go
  testutil/client.go
  testutil/zero.go
  tlstest/mtls_internal/ha_6_node/ha_test.go
  tlstest/mtls_internal/multi_group/multi_group_test.go
  tlstest/mtls_internal/single_node/single_node_test.go
  x/x.go
Labels: area/testing, area/enterprise, area/graphql, area/bulk-loader, area/enterprise/backup, area/core, go

#9347 fix(core): fix unmarshal protobuf when len val is 0
  schema/schema.go
  worker/sort_test.go
Labels: area/testing, area/schema, area/core, go

#9348 fix(core): put new metrics behind a feature flag (#9337)
  dgraph/cmd/alpha/run.go
  posting/lists.go
  posting/mvcc.go
  worker/server_state.go
Labels: area/core, go

#9350 fix(core): fix read scalar list with rollups
  posting/oracle.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9351 fix(core): fix read scalar list with rollups (#9350)
  posting/oracle.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9355 Add implementation for RunDQL for v25
  dgraph/cmd/alpha/http.go
  dgraph/cmd/alpha/http_test.go
  dql/dql.go
  dql/dql_test.go
  dql/parser_mutation.go
  dql/parser_test.go
  dql/state.go
  dql/upsert_test.go
  edgraph/alter.go
  edgraph/namespace.go
  edgraph/namespace_test.go
  edgraph/query.go
  go.mod
  go.sum
Labels: area/testing, area/querylang, go

#9365 undo the breaking change made while removing sentry flag
  dgraph/docker-compose.yml
  x/flags.go
Labels: area/core, go

#9364 undo the breaking change made while removing sentry flag
  dgraph/docker-compose.yml
  x/flags.go
Labels: area/core, go
