Repository hypermodeinc/dgraph, pull requests merged in 2025-04, with the labels that each got.

#9367 remove enterprise license completely from dgraph
  .github/workflows/ci-dgraph-core-tests.yml
  .github/workflows/ci-dgraph-system-upgrade-tests.yml
  .trunk/trunk.yaml
  dgraph/cmd/alpha/run.go
  dgraph/cmd/bulk/run.go
  dgraph/cmd/zero/http.go
  dgraph/cmd/zero/license.go
  dgraph/cmd/zero/license_ee.go
  dgraph/cmd/zero/pgp.go
  dgraph/cmd/zero/pgp_test.go
  dgraph/cmd/zero/raft.go
  dgraph/cmd/zero/run.go
  dgraph/cmd/zero/zero.go
  dgraphapi/cluster.go
  edgraph/access_ee.go
  ee/acl/acl_integration_test.go
  ee/audit/audit.go
  ee/audit/audit_ee.go
  graphql/admin/admin.go
  graphql/admin/backup.go
  graphql/admin/endpoints_ee.go
  graphql/admin/enterpriseLicense.go
  graphql/admin/state.go
  graphql/e2e/common/admin.go
  protos/pb.proto
  protos/pb/pb.pb.go
  protos/pb/pb_grpc.pb.go
  query/query.go
  systest/audit/audit_test.go
  systest/license/docker-compose.yml
  systest/license/integration_test.go
  systest/license/license_test.go
  systest/license/upgrade_test.go
  testutil/graphql.go
  testutil/testaudit/audit.go
  tlstest/tls/client.acl.crt
  tlstest/tls/client.acl.key
  tlstest/tls/node.crt
  tlstest/tls/node.key
  worker/cdc_ee.go
  worker/groups.go
  worker/server_state.go
  worker/zero.go
  x/x.go
Labels: area/testing, area/enterprise, area/graphql, area/integrations, area/bulk-loader, area/enterprise/acl, area/core, go

#9310 fix(core): upgrade opencensus to opentelemetry
  conn/node.go
  conn/pool.go
  conn/raft_server.go
  dgraph/cmd/alpha/run.go
  dgraph/cmd/zero/assign.go
  dgraph/cmd/zero/oracle.go
  dgraph/cmd/zero/raft.go
  dgraph/cmd/zero/run.go
  dgraph/cmd/zero/tablet.go
  dgraph/cmd/zero/zero.go
  edgraph/alter.go
  edgraph/server.go
  go.mod
  go.sum
  graphql/resolve/mutation.go
  graphql/resolve/query.go
  graphql/resolve/resolver.go
  posting/index.go
  query/mutation.go
  query/query.go
  worker/draft.go
  worker/mutation.go
  worker/predicate_move.go
  worker/proposal.go
  worker/schema.go
  worker/sort.go
  worker/task.go
  worker/worker.go
  x/metrics.go
  x/x.go
Labels: area/graphql, area/core, go

#9374 fix(graphql): fix error handling in webhooks
  graphql/resolve/webhook.go
Labels: area/graphql, area/core, go

#9377 handle the case for root namespace in namespace and other grpc API
  edgraph/namespace.go
Labels: go

#9378 fix(core): fix old deletes for scalar postings
  posting/list.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9380 fix(core): delete all before set for scalar postings (#9378)
  posting/list.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9388 Fix bugs in v25 RunDQL API
  edgraph/query.go
Labels: go

#9382 fix(core): Add maxfrontiersize to shortest path query
  dql/parser.go
  dql/parser_test.go
  query/query.go
  query/shortest.go
  systest/shortest-path/graph.rdf.gz
  systest/shortest-path/graph.schema.gz
  systest/shortest-path/shortest_test.go
Labels: area/testing, area/querylang, area/core, go

#9383 perf(core): improve performance for ineq filters when uidlist is small
  worker/task.go
Labels: area/core, go

#9309 fix(live): fix how xidmap stores value along with upsertPredicate
  dgraph/cmd/live/batch.go
  xidmap/xidmap.go
Labels: area/live-loader, area/core, go

#9376 remove telemetry from alpha and push very basic telemetry in zero
  dgraph/cmd/alpha/mutations_mode/docker-compose.yml
  dgraph/cmd/alpha/run.go
  dgraph/cmd/zero/run.go
  dgraph/cmd/zero/zero.go
  dgraph/docker-compose.yml
  edgraph/server.go
  graphql/e2e/admin_auth/poorman_auth/docker-compose.yml
  graphql/e2e/admin_auth/poorman_auth_with_acl/docker-compose.yml
  graphql/e2e/auth/debug_off/docker-compose.yml
  graphql/e2e/auth/docker-compose.yml
  graphql/e2e/auth_closed_by_default/docker-compose.yml
  graphql/e2e/custom_logic/docker-compose.yml
  graphql/e2e/directives/docker-compose.yml
  graphql/e2e/multi_tenancy/docker-compose.yml
  graphql/e2e/normal/docker-compose.yml
  graphql/e2e/schema/docker-compose.yml
  graphql/e2e/subscription/docker-compose.yml
  graphql/testdata/custom_bench/profiling/docker-compose.yml
  ocagent/docker-compose.yml
  systest/1million/alpha.yml
  systest/21million/bulk/alpha.yml
  systest/21million/live/docker-compose.yml
  systest/acl/restore/docker-compose.yml
  systest/audit/docker-compose.yml
  systest/audit_encrypted/docker-compose.yml
  systest/backup/advanced-scenarios/127-Namespace/docker-compose.yml
  systest/backup/advanced-scenarios/acl-nonAcl/docker-compose.yml
  systest/backup/advanced-scenarios/deleted-namespace/docker-compose.yml
  systest/backup/encryption/docker-compose.yml
  systest/backup/filesystem/docker-compose.yml
  systest/backup/minio-large/docker-compose.yml
  systest/backup/minio/docker-compose.yml
  systest/backup/multi-tenancy/docker-compose.yml
  systest/backup/nfs-backup/docker-compose.yml
  systest/bgindex/docker-compose.yml
  systest/bulk_live/bulk/alpha.yml
  systest/bulk_live/bulk/alpha_acl.yml
  systest/bulk_live/live/docker-compose.yml
  systest/cdc/docker-compose.yml
  systest/cloud/docker-compose.yml
  systest/export/docker-compose.yml
  systest/group-delete/docker-compose.yml
  systest/ldbc/alpha.yml
  systest/loader/docker-compose.yml
  systest/multi-tenancy/docker-compose.yml
  systest/online-restore/docker-compose.yml
  systest/plugin/docker-compose.yml
  telemetry/telemetry.go
  testutil/testaudit/docker-compose.yml
  tlstest/acl/docker-compose.yml
  tlstest/certrequest/docker-compose.yml
  tlstest/certrequireandverify/docker-compose.yml
  tlstest/certverifyifgiven/docker-compose.yml
  tlstest/mtls_internal/ha_6_node/docker-compose.yml
  tlstest/mtls_internal/multi_group/docker-compose.yml
  tlstest/mtls_internal/single_node/docker-compose.yml
  tlstest/zero_https/all_routes_tls/docker-compose.yml
  tlstest/zero_https/no_tls/docker-compose.yml
  worker/docker-compose.yml
Labels: area/testing, area/graphql, area/core, go

#9394 fix(core): fix variables in live loader
  dgraph/cmd/live/batch.go
Labels: area/live-loader, go

#9395 update the URL for sending telemetry
  dgraph/cmd/zero/zero.go
Labels: go

#9370 upgrade Go to v1.24, Go deps and trunk upgrade, and golangci upgrade to v2
  .trunk/configs/.golangci.json
  .trunk/trunk.yaml
  algo/uidlist_test.go
  codec/codec_test.go
  dgraph/cmd/live/batch.go
  dgraph/cmd/live/run.go
  dgraph/main.go
  dql/parser.go
  edgraph/access.go
  edgraph/server.go
  go.mod
  go.sum
  graphql/e2e/auth/sample_private_key.pem
  graphql/e2e/auth/sample_public_key.pem
  graphql/e2e/custom_logic/cmd/go.mod
  graphql/resolve/mutation_rewriter.go
  graphql/resolve/resolver_error_test.go
  graphql/schema/auth.go
  graphql/schema/rules.go
  graphql/schema/validation_rules.go
  graphql/testdata/datagen/cmd/run.go
  posting/list.go
  raftwal/encryption_test.go
  systest/backup/advanced-scenarios/deleted-namespace/backup_test.go
  systest/backup/encryption/backup_test.go
  systest/mutations-and-queries/mutations_test.go
  systest/unique_test.go
  t/Makefile
  t/t.go
  testutil/bulk.go
  testutil/client.go
  testutil/multi_tenancy.go
  worker/draft.go
  worker/groups.go
  worker/mutation.go
  x/error.go
Labels: area/testing, area/querylang, area/graphql, area/live-loader, area/core, go

#9398 fix(core): fix TestLiveLoadAndExportRDFFormat test
  worker/export.go
  worker/mutation.go
Labels: area/core, go

#9401 add test cases for dot product with constant vector
  query/vector/vector_test.go
Labels: area/testing, area/core, go
