Repository hypermodeinc/dgraph, pull requests merged in 2025-09, with the labels that each got.

#9500 chore(tests): Future-proof whitelist against Docker network changes
  compose/compose.go
  dgraph/cmd/alpha/mutations_mode/docker-compose.yml
  dgraph/docker-compose.yml
  dgraphtest/dgraph.go
  graphql/e2e/admin_auth/poorman_auth/docker-compose.yml
  graphql/e2e/admin_auth/poorman_auth_with_acl/docker-compose.yml
  graphql/e2e/auth/debug_off/docker-compose.yml
  graphql/e2e/auth/docker-compose.yml
  graphql/e2e/auth_closed_by_default/docker-compose.yml
  graphql/e2e/custom_logic/docker-compose.yml
  graphql/e2e/directives/docker-compose.yml
  graphql/e2e/multi_tenancy/docker-compose.yml
  graphql/e2e/normal/docker-compose.yml
  graphql/e2e/schema/docker-compose.yml
  graphql/e2e/subscription/docker-compose.yml
  graphql/testdata/custom_bench/profiling/docker-compose.yml
  systest/1million/alpha.yml
  systest/21million/bulk/alpha.yml
  systest/acl/restore/docker-compose.yml
  systest/audit/docker-compose.yml
  systest/audit_encrypted/docker-compose.yml
  systest/backup/advanced-scenarios/127-Namespace/docker-compose.yml
  systest/backup/advanced-scenarios/acl-nonAcl/docker-compose.yml
  systest/backup/advanced-scenarios/deleted-namespace/docker-compose.yml
  systest/backup/encryption/docker-compose.yml
  systest/backup/filesystem/docker-compose.yml
  systest/backup/minio-large/docker-compose.yml
  systest/backup/minio/docker-compose.yml
  systest/backup/multi-tenancy/docker-compose.yml
  systest/backup/nfs-backup/docker-compose.yml
  systest/bgindex/docker-compose.yml
  systest/bulk_live/live/docker-compose.yml
  systest/cdc/docker-compose.yml
  systest/cloud/docker-compose.yml
  systest/export/docker-compose.yml
  systest/group-delete/docker-compose.yml
  systest/ldbc/alpha.yml
  systest/loader-benchmark/docker-compose.yml
  systest/loader/docker-compose.yml
  systest/multi-tenancy/docker-compose.yml
  systest/online-restore/docker-compose.yml
  systest/plugin/docker-compose.yml
  testutil/testaudit/docker-compose.yml
  tlstest/acl/docker-compose.yml
  tlstest/certrequest/docker-compose.yml
  tlstest/certrequireandverify/docker-compose.yml
  tlstest/certverifyifgiven/docker-compose.yml
  tlstest/mtls_internal/ha_6_node/docker-compose.yml
  tlstest/mtls_internal/multi_group/docker-compose.yml
  tlstest/mtls_internal/single_node/docker-compose.yml
  tlstest/zero_https/all_routes_tls/docker-compose.yml
  tlstest/zero_https/no_tls/docker-compose.yml
  worker/docker-compose.yml
Labels: area/testing, area/graphql, area/core, go

#9499 chore(test): Improve localcluster tests speed and resiliency
  .github/workflows/ci-dgraph-vector-tests.yml
  dgraph/cmd/dgraphimport/import_test.go
  dgraphtest/image.go
  dgraphtest/load.go
  dgraphtest/local_cluster.go
  testutil/docker.go
Labels: area/testing, area/integrations, go

#9505 Fix bugs with namespaces and add back tests
  edgraph/alter_test.go
  edgraph/namespace.go
  edgraph/namespace_test.go
  edgraph/query.go
  go.mod
  go.sum
Labels: area/testing, go
