Repository hypermodeinc/dgraph, pull requests merged in 2025-08, with the labels that each got.

#9450 fix(core): add additional checks in verifyUniqueWithinMutation for pruned mutations
  CHANGELOG.md
  dgraph/cmd/alpha/run_test.go
  dgraphtest/image.go
  edgraph/server.go
  edgraph/server_test.go
Labels: area/testing, area/documentation, go

#9480 fix(core): Fix race condition in mutation map (#9473)
  posting/index_test.go
  posting/list.go
  posting/list_test.go
  posting/mvcc.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9485 chore(test): Increase performance of t-harness tests
  .github/workflows/ci-dgraph-core-tests.yml
  acl/acl_curl_test.go
  check_upgrade/check_upgrade_test.go
  dgraph/cmd/dgraphimport/import_test.go
  dgraph/cmd/increment/increment_test.go
  dgraph/cmd/live/load-json/load_test.go
  dgraph/cmd/live/load-uids/load_test.go
  dgraph/cmd/version/version_test.go
  dgraph/cmd/zero/zero_test.go
  dgraph/docker-compose.yml
  dgraphtest/compose_cluster.go
  dgraphtest/local_cluster.go
  graphql/e2e/schema/schema_test.go
  query/common_test.go
  systest/1million/1million_test.go
  systest/21million/bulk/run_test.go
  systest/acl/restore/acl_restore_test.go
  systest/audit/audit_test.go
  systest/audit_encrypted/audit_test.go
  systest/backup/encryption/backup_test.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio-large/backup_test.go
  systest/backup/minio/backup_test.go
  systest/backup/multi-tenancy/backup_test.go
  systest/backup/nfs-backup/backup_test.go
  systest/bgindex/count_test.go
  systest/bgindex/parallel_test.go
  systest/bgindex/reverse_test.go
  systest/bgindex/string_test.go
  systest/cdc/cdc_test.go
  systest/export/export_test.go
  systest/group-delete/group_delete_test.go
  systest/integration2/bulk_loader_test.go
  systest/ldbc/ldbc_test.go
  systest/live_pw_test.go
  systest/loader/loader_test.go
  systest/online-restore/online_restore_test.go
  t/t.go
  testutil/client.go
  testutil/docker.go
  testutil/graphql.go
  testutil/minio.go
  testutil/multi_tenancy.go
  testutil/testaudit/audit.go
  testutil/zero.go
  tlstest/acl/acl_over_tls_test.go
  tlstest/certrequest/certrequest_test.go
  tlstest/certrequireandverify/certrequireandverify_test.go
  tlstest/certverifyifgiven/certverifyifgiven_test.go
  tlstest/mtls_internal/multi_group/multi_group_test.go
  tlstest/mtls_internal/single_node/single_node_test.go
  tlstest/zero_https/all_routes_tls/all_routes_tls_test.go
  tlstest/zero_https/no_tls/no_tls_test.go
  worker/export_test.go
  worker/snapshot_test.go
  worker/worker_test.go
  xidmap/xidmap_test.go
Labels: area/testing, area/graphql, area/integrations, area/live-loader, area/acl, area/core, go

#9492 fix(query): return full float value in query results
  CHANGELOG.md
  graphql/e2e/common/fragment.go
  query/fastjson_test.go
  query/outputnode.go
  query/outputnode_test.go
  query/query0_test.go
  query/query1_test.go
  query/query3_test.go
  query/query4_test.go
  systest/1million/common/tc.go
  systest/21million/queries/query-039
  systest/21million/queries/query-045
Labels: kind/bug, dgraph
