Repository hypermodeinc/dgraph, pull requests merged in 2025-01, with the labels that each got.

#9253 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/documentation, area/integrations

#9251 ci: Add cron job to run workflow once a day
  .github/workflows/ci-dgraph-core-tests.yml
  .github/workflows/ci-dgraph-systest-tests.yml
  .github/workflows/ci-dgraph-vector-tests.yml
Labels: area/integrations

#9237 perf(core): Fixing ristretto cache to pass jepsen tests
  dgraph/cmd/alpha/run.go
  dgraph/cmd/debug/run.go
  go.mod
  go.sum
  posting/index.go
  posting/index_test.go
  posting/list.go
  posting/list_test.go
  posting/lists.go
  posting/mvcc.go
  posting/mvcc_test.go
  posting/oracle.go
  systest/21million/bulk/run_test.go
  worker/config.go
  worker/draft.go
  worker/mutation_unit_test.go
  worker/online_restore.go
  worker/server_state.go
  worker/sort_test.go
  worker/worker_test.go
  x/keys.go
Labels: area/testing, area/core, go

#9274 fix(core): Change name of new config flag
  dgraph/cmd/alpha/run.go
  posting/lists.go
  posting/mvcc.go
  worker/config.go
  worker/server_state.go
Labels: area/core, go

#9218 perf(core): Add a count min sketch for eq filter
  algo/cm-sketch.go
  dgraph/cmd/alpha/run.go
  go.mod
  go.sum
  posting/mvcc.go
  posting/stats.go
  worker/config.go
  worker/task.go
  worker/worker_test.go
Labels: area/testing, area/core, go

#9278 chore: make testing more resilient and update docs
  CONTRIBUTING.md
  dgraph/Makefile
  dgraphtest/image.go
  dgraphtest/local_cluster.go
  ee/acl/acl_curl_test.go
  protos/protos_test.go
  systest/audit/audit_test.go
  systest/audit_encrypted/audit_test.go
  systest/loader/loader_test.go
  t/Makefile
  t/README.md
  t/t.go
  testutil/client.go
  testutil/testaudit/audit.go
  tlstest/certrequest/certrequest_test.go
Labels: area/testing, area/documentation, area/enterprise, area/enterprise/acl, area/core, go

#9284 fix: compile on Windows
  x/x.go
Labels: area/core, go

#9288 fix(core): fix race in metrics collection variables
  go.mod
  go.sum
  posting/mvcc.go
Labels: area/core, go

#9280 feat(graphql): output translated DQL query when the graphql debug superflag is set
  CHANGELOG.md
  graphql/e2e/common/common.go
  graphql/e2e/common/query.go
  graphql/e2e/directives/docker-compose.yml
  graphql/e2e/normal/docker-compose.yml
  graphql/resolve/query.go
  graphql/schema/response.go
Labels: area/testing, area/documentation, area/graphql, area/core, area/dql-graphql-interop, go

#9296 fix(core): Fix deleteBelowTs rollup issue
  posting/list.go
  worker/task.go
Labels: area/core, go

#9292 fix(core): Fix count index for scalar predicates
  posting/index.go
  posting/list.go
  worker/sort_test.go
Labels: area/testing, area/core, go

#9282 add internal predicate for string namespaces
  .github/workflows/ci-dgraph-core-upgrade-tests.yml
  .github/workflows/ci-dgraph-fuzz.yml
  .github/workflows/ci-dgraph-oss-build.yml
  .github/workflows/ci-dgraph-system-upgrade-tests.yml
  .github/workflows/ci-dgraph-upgrade-fixed-versions-tests.yml
  contrib/Dockerfile
  dgraphtest/config.go
  dgraphtest/dgraph.go
  dgraphtest/image.go
  edgraph/server.go
  ee/acl/acl_test.go
  ee/acl/upgrade_test.go
  graphql/e2e/directives/schema_response.json
  graphql/e2e/normal/schema_response.json
  query/upgrade_test.go
  schema/schema.go
  systest/backup/filesystem/backup_test.go
  systest/backup/minio/backup_test.go
  systest/export/export_test.go
  systest/integration2/acl_test.go
  systest/mutations-and-queries/integration_test.go
  systest/mutations-and-queries/mutations_test.go
  systest/mutations-and-queries/queries_test.go
  systest/mutations-and-queries/upgrade_test.go
  testutil/schema.go
  worker/groups.go
  worker/online_restore.go
  x/keys.go
Labels: area/testing, area/enterprise, area/schema, area/graphql, area/integrations, area/enterprise/acl, area/core, go

#9298 fix(core): Added some metrics
  edgraph/server.go
  posting/mvcc.go
  systest/backup/minio/docker-compose.yml
  worker/task.go
  x/metrics.go
Labels: area/testing, area/core, go

#9290 perf(core): Add scalar list to mutations
  posting/lists.go
  posting/mvcc.go
  posting/oracle.go
  worker/mutation.go
  x/metrics.go
Labels: area/core, go
